; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/music/bike_riding.asm
Music_BikeRiding_Ch1::
	sound_ret
Music_BikeRiding_Ch2::
	sound_ret
Music_BikeRiding_Ch3::
	sound_ret
Music_BikeRiding_Ch4::
	sound_ret

; from audio/music/celadon.asm
Music_Celadon_Ch1::
	sound_ret
Music_Celadon_Ch2::
	sound_ret
Music_Celadon_Ch3::
	sound_ret

; from audio/music/cinnabar.asm
Music_Cinnabar_Ch1::
	sound_ret
Music_Cinnabar_Ch2::
	sound_ret
Music_Cinnabar_Ch3::
	sound_ret

; from audio/music/cinnabar_mansion.asm
Music_CinnabarMansion_Ch1::
	sound_ret
Music_CinnabarMansion_Ch2::
	sound_ret
Music_CinnabarMansion_Ch3::
	sound_ret
Music_CinnabarMansion_Ch4::
	sound_ret

; from audio/music/cities_1.asm
Music_Cities1_Ch1_AlternateTempo::
	sound_ret
Music_Cities1_Ch1::
	sound_ret
Music_Cities1_Ch2::
	sound_ret
Music_Cities1_Ch3::
	sound_ret
Music_Cities1_Ch4::
	sound_ret

; from audio/music/cities_2.asm
Music_Cities2_Ch1::
	sound_ret
Music_Cities2_Ch2::
	sound_ret
Music_Cities2_Ch3::
	sound_ret

; from audio/music/credits.asm
Music_Credits_Ch1::
	sound_ret
Music_Credits_Ch2::
	sound_ret
Music_Credits_Ch3::
	sound_ret

; from audio/music/defeated_gym_leader.asm
Music_DefeatedGymLeader_Ch1::
	sound_ret
Music_DefeatedGymLeader_Ch2::
	sound_ret
Music_DefeatedGymLeader_Ch3::
	sound_ret

; from audio/music/defeated_trainer.asm
Music_DefeatedTrainer_Ch1::
	sound_ret
Music_DefeatedTrainer_Ch2::
	sound_ret
Music_DefeatedTrainer_Ch3::
	sound_ret

; from audio/music/defeated_wild_mon.asm
Music_DefeatedWildMon_Ch1::
	sound_ret
Music_DefeatedWildMon_Ch2::
	sound_ret
Music_DefeatedWildMon_Ch3::
	sound_ret

; from audio/music/dungeon_1.asm
Music_Dungeon1_Ch1::
	sound_ret
Music_Dungeon1_Ch2::
	sound_ret
Music_Dungeon1_Ch3::
	sound_ret
Music_Dungeon1_Ch4::
	sound_ret

; from audio/music/dungeon_2.asm
Music_Dungeon2_Ch1::
	sound_ret
Music_Dungeon2_Ch2::
	sound_ret
Music_Dungeon2_Ch3::
	sound_ret
Music_Dungeon2_Ch4::
	sound_ret

; from audio/music/dungeon_3.asm
Music_Dungeon3_Ch1::
	sound_ret
Music_Dungeon3_Ch2::
	sound_ret
Music_Dungeon3_Ch3::
	sound_ret
Music_Dungeon3_Ch4::
	sound_ret

; from audio/music/final_battle.asm
Music_FinalBattle_Ch1::
	sound_ret
Music_FinalBattle_Ch2::
	sound_ret
Music_FinalBattle_Ch3::
	sound_ret

; from audio/music/game_corner.asm
Music_GameCorner_Ch1::
	sound_ret
Music_GameCorner_Ch2::
	sound_ret
Music_GameCorner_Ch3::
	sound_ret

; from audio/music/gym.asm
Music_Gym_Ch1::
	sound_ret
Music_Gym_Ch2::
	sound_ret
Music_Gym_Ch3::
	sound_ret

; from audio/music/gym_leader_battle.asm
Music_GymLeaderBattle_Ch1::
	sound_ret
Music_GymLeaderBattle_Ch2::
	sound_ret
Music_GymLeaderBattle_Ch3::
	sound_ret

; from audio/music/hall_of_fame.asm
Music_HallOfFame_Ch1::
	sound_ret
Music_HallOfFame_Ch2::
	sound_ret
Music_HallOfFame_Ch3::
	sound_ret

; from audio/music/indigo_plateau.asm
Music_IndigoPlateau_Ch1::
	sound_ret
Music_IndigoPlateau_Ch2::
	sound_ret
Music_IndigoPlateau_Ch3::
	sound_ret
Music_IndigoPlateau_Ch4::
	sound_ret

; from audio/music/intro_battle.asm
Music_IntroBattle_Ch1::
	sound_ret
Music_IntroBattle_Ch2::
	sound_ret
Music_IntroBattle_Ch3::
	sound_ret
Music_IntroBattle_Ch4::
	sound_ret

; from audio/music/jigglypuff_song.asm
Music_JigglypuffSong_Ch1::
	sound_ret
Music_JigglypuffSong_Ch2::
	sound_ret

; from audio/music/lavender.asm
Music_Lavender_Ch1::
	sound_ret
Music_Lavender_Ch2::
	sound_ret
Music_Lavender_Ch3::
	sound_ret
Music_Lavender_Ch4::
	sound_ret

; from audio/music/meet_evil_trainer.asm
Music_MeetEvilTrainer_Ch1::
	sound_ret
Music_MeetEvilTrainer_Ch2::
	sound_ret
Music_MeetEvilTrainer_Ch3::
	sound_ret

; from audio/music/meet_female_trainer.asm
Music_MeetFemaleTrainer_Ch1::
	sound_ret
Music_MeetFemaleTrainer_Ch2::
	sound_ret
Music_MeetFemaleTrainer_Ch3::
	sound_ret

; from audio/music/meet_male_trainer.asm
Music_MeetMaleTrainer_Ch1::
	sound_ret
Music_MeetMaleTrainer_Ch2::
	sound_ret
Music_MeetMaleTrainer_Ch3::
	sound_ret

; from audio/music/meet_prof_oak.asm
Music_MeetProfOak_Ch1::
	sound_ret
Music_MeetProfOak_Ch2::
	sound_ret
Music_MeetProfOak_Ch3::
	sound_ret

; from audio/music/meet_rival.asm
Music_MeetRival_Ch1_AlternateTempo::
	sound_ret
Music_MeetRival_Ch1::
	sound_ret
Music_MeetRival_Ch1_AlternateStartAndTempo::
	sound_ret
Music_MeetRival_Ch1_AlternateStart::
	sound_ret
Music_MeetRival_Ch2::
	sound_ret
Music_MeetRival_Ch2_AlternateStart::
	sound_ret
Music_MeetRival_Ch3::
	sound_ret
Music_MeetRival_Ch3_AlternateStart::
	sound_ret

; from audio/music/museum_guy.asm
Music_MuseumGuy_Ch1::
	sound_ret
Music_MuseumGuy_Ch2::
	sound_ret
Music_MuseumGuy_Ch3::
	sound_ret
Music_MuseumGuy_Ch4::
	sound_ret

; from audio/music/oaks_lab.asm
Music_OaksLab_Ch1::
	sound_ret
Music_OaksLab_Ch2::
	sound_ret
Music_OaksLab_Ch3::
	sound_ret

; from audio/music/pallet_town.asm
Music_PalletTown_Ch1::
	sound_ret
Music_PalletTown_Ch2::
	sound_ret
Music_PalletTown_Ch3::
	sound_ret

; from audio/music/pkmn_healed.asm
Music_PkmnHealed_Ch1::
	sound_ret
Music_PkmnHealed_Ch2::
	sound_ret
Music_PkmnHealed_Ch3::
	sound_ret

; from audio/music/pokecenter.asm
Music_Pokecenter_Ch1::
	sound_ret
Music_Pokecenter_Ch2::
	sound_ret
Music_Pokecenter_Ch3::
	sound_ret

; from audio/music/pokemon_tower.asm
Music_PokemonTower_Ch1::
	sound_ret
Music_PokemonTower_Ch2::
	sound_ret
Music_PokemonTower_Ch3::
	sound_ret

; from audio/music/routes_1.asm
Music_Routes1_Ch1::
	sound_ret
Music_Routes1_Ch2::
	sound_ret
Music_Routes1_Ch3::
	sound_ret
Music_Routes1_Ch4::
	sound_ret

; from audio/music/routes_2.asm
Music_Routes2_Ch1::
	sound_ret
Music_Routes2_Ch2::
	sound_ret
Music_Routes2_Ch3::
	sound_ret
Music_Routes2_Ch4::
	sound_ret

; from audio/music/routes_3.asm
Music_Routes3_Ch1::
	sound_ret
Music_Routes3_Ch2::
	sound_ret
Music_Routes3_Ch3::
	sound_ret
Music_Routes3_Ch4::
	sound_ret

; from audio/music/routes_4.asm
Music_Routes4_Ch1::
	sound_ret
Music_Routes4_Ch2::
	sound_ret
Music_Routes4_Ch3::
	sound_ret
Music_Routes4_Ch4::
	sound_ret

; from audio/music/safari_zone.asm
Music_SafariZone_Ch1::
	sound_ret
Music_SafariZone_Ch2::
	sound_ret
Music_SafariZone_Ch3::
	sound_ret

; from audio/music/silph_co.asm
Music_SilphCo_Ch1::
	sound_ret
Music_SilphCo_Ch2::
	sound_ret
Music_SilphCo_Ch3::
	sound_ret

; from audio/music/ss_anne.asm
Music_SSAnne_Ch1::
	sound_ret
Music_SSAnne_Ch2::
	sound_ret
Music_SSAnne_Ch3::
	sound_ret

; from audio/music/surfing.asm
Music_Surfing_Ch1::
	sound_ret
Music_Surfing_Ch2::
	sound_ret
Music_Surfing_Ch3::
	sound_ret

; from audio/music/title_screen.asm
Music_TitleScreen_Ch1::
	sound_ret
Music_TitleScreen_Ch2::
	sound_ret
Music_TitleScreen_Ch3::
	sound_ret
Music_TitleScreen_Ch4::
	sound_ret

; from audio/music/trainer_battle.asm
Music_TrainerBattle_Ch1::
	sound_ret
Music_TrainerBattle_Ch2::
	sound_ret
Music_TrainerBattle_Ch3::
	sound_ret

; from audio/music/unused_song.asm
Music_UnusedSong_Ch1::
	sound_ret
Music_UnusedSong_Ch2::
	sound_ret

; from audio/music/vermilion.asm
Music_Vermilion_Ch1::
	sound_ret
Music_Vermilion_Ch2::
	sound_ret
Music_Vermilion_Ch3::
	sound_ret
Music_Vermilion_Ch4::
	sound_ret

; from audio/music/wild_battle.asm
Music_WildBattle_Ch1::
	sound_ret
Music_WildBattle_Ch2::
	sound_ret
Music_WildBattle_Ch3::
	sound_ret

; from audio/sfx/59.asm
SFX_59_1_Ch5::
	sound_ret
SFX_59_2_Ch5::
	sound_ret
SFX_59_3_Ch5::
	sound_ret
SFX_59_1_Ch6::
	sound_ret
SFX_59_2_Ch6::
	sound_ret
SFX_59_3_Ch6::
	sound_ret

; from audio/sfx/arrow_tiles.asm
SFX_Arrow_Tiles_1_Ch5::
	sound_ret
SFX_Arrow_Tiles_2_Ch5::
	sound_ret
SFX_Arrow_Tiles_3_Ch5::
	sound_ret

; from audio/sfx/ball_poof.asm
SFX_Ball_Poof_Ch5::
	sound_ret
SFX_Ball_Poof_Ch8::
	sound_ret

; from audio/sfx/ball_toss.asm
SFX_Ball_Toss_Ch5::
	sound_ret
SFX_Ball_Toss_Ch6::
	sound_ret

; from audio/sfx/battle_09.asm
SFX_Battle_09_Ch5::
	sound_ret

; from audio/sfx/battle_0b.asm
SFX_Battle_0B_Ch8::
	sound_ret

; from audio/sfx/battle_0c.asm
SFX_Battle_0C_Ch8::
	sound_ret

; from audio/sfx/battle_0d.asm
SFX_Battle_0D_Ch8::
	sound_ret

; from audio/sfx/battle_0e.asm
SFX_Battle_0E_Ch8::
	sound_ret

; from audio/sfx/battle_0f.asm
SFX_Battle_0F_Ch8::
	sound_ret

; from audio/sfx/battle_12.asm
SFX_Battle_12_Ch8::
	sound_ret

; from audio/sfx/battle_13.asm
SFX_Battle_13_Ch8::
	sound_ret

; from audio/sfx/battle_14.asm
SFX_Battle_14_Ch8::
	sound_ret

; from audio/sfx/battle_16.asm
SFX_Battle_16_Ch8::
	sound_ret

; from audio/sfx/battle_17.asm
SFX_Battle_17_Ch8::
	sound_ret

; from audio/sfx/battle_18.asm
SFX_Battle_18_Ch8::
	sound_ret

; from audio/sfx/battle_19.asm
SFX_Battle_19_Ch8::
	sound_ret

; from audio/sfx/battle_1b.asm
SFX_Battle_1B_Ch8::
	sound_ret

; from audio/sfx/battle_1c.asm
SFX_Battle_1C_Ch8::
	sound_ret

; from audio/sfx/battle_1e.asm
SFX_Battle_1E_Ch5::
	sound_ret
SFX_Battle_1E_Ch8::
	sound_ret

; from audio/sfx/battle_20.asm
SFX_Battle_20_Ch8::
	sound_ret

; from audio/sfx/battle_21.asm
SFX_Battle_21_Ch8::
	sound_ret

; from audio/sfx/battle_22.asm
SFX_Battle_22_Ch8::
	sound_ret

; from audio/sfx/battle_23.asm
SFX_Battle_23_Ch8::
	sound_ret

; from audio/sfx/battle_24.asm
SFX_Battle_24_Ch5::
	sound_ret
SFX_Battle_24_Ch8::
	sound_ret

; from audio/sfx/battle_25.asm
SFX_Battle_25_Ch8::
	sound_ret

; from audio/sfx/battle_26.asm
SFX_Battle_26_Ch8::
	sound_ret

; from audio/sfx/battle_27.asm
SFX_Battle_27_Ch5::
	sound_ret
SFX_Battle_27_Ch6::
	sound_ret
SFX_Battle_27_Ch8::
	sound_ret

; from audio/sfx/battle_28.asm
SFX_Battle_28_Ch5::
	sound_ret
SFX_Battle_28_Ch6::
	sound_ret
SFX_Battle_28_Ch8::
	sound_ret

; from audio/sfx/battle_29.asm
SFX_Battle_29_Ch5::
	sound_ret
SFX_Battle_29_Ch8::
	sound_ret

; from audio/sfx/battle_2a.asm
SFX_Battle_2A_Ch5::
	sound_ret
SFX_Battle_2A_Ch6::
	sound_ret
SFX_Battle_2A_Ch8::
	sound_ret

; from audio/sfx/battle_2b.asm
SFX_Battle_2B_Ch5::
	sound_ret
SFX_Battle_2B_Ch8::
	sound_ret

; from audio/sfx/battle_2c.asm
SFX_Battle_2C_Ch5::
	sound_ret
SFX_Battle_2C_Ch6::
	sound_ret
SFX_Battle_2C_Ch8::
	sound_ret

; from audio/sfx/battle_2e.asm
SFX_Battle_2E_Ch5::
	sound_ret
SFX_Battle_2E_Ch6::
	sound_ret
SFX_Battle_2E_Ch8::
	sound_ret

; from audio/sfx/battle_2f.asm
SFX_Battle_2F_Ch5::
	sound_ret
SFX_Battle_2F_Ch6::
	sound_ret
SFX_Battle_2F_Ch8::
	sound_ret

; from audio/sfx/battle_31.asm
SFX_Battle_31_Ch5::
	sound_ret
SFX_Battle_31_Ch6::
	sound_ret

; from audio/sfx/battle_32.asm
SFX_Battle_32_Ch5::
	sound_ret
SFX_Battle_32_Ch6::
	sound_ret

; from audio/sfx/battle_33.asm
SFX_Battle_33_Ch5::
	sound_ret
SFX_Battle_33_Ch6::
	sound_ret

; from audio/sfx/battle_34.asm
SFX_Battle_34_Ch5::
	sound_ret
SFX_Battle_34_Ch6::
	sound_ret
SFX_Battle_34_Ch8::
	sound_ret

; from audio/sfx/battle_35.asm
SFX_Battle_35_Ch5::
	sound_ret
SFX_Battle_35_Ch6::
	sound_ret

; from audio/sfx/battle_36.asm
SFX_Battle_36_Ch5::
	sound_ret
SFX_Battle_36_Ch6::
	sound_ret
SFX_Battle_36_Ch8::
	sound_ret

; from audio/sfx/caught_mon.asm
SFX_Caught_Mon_Ch5::
	sound_ret
SFX_Caught_Mon_Ch6::
	sound_ret
SFX_Caught_Mon_Ch7::
	sound_ret

; from audio/sfx/collision.asm
SFX_Collision_1_Ch5::
	sound_ret
SFX_Collision_2_Ch5::
	sound_ret
SFX_Collision_3_Ch5::
	sound_ret

; from audio/sfx/cry00.asm
SFX_Cry00_1_Ch5::
	sound_ret
SFX_Cry00_2_Ch5::
	sound_ret
SFX_Cry00_3_Ch5::
	sound_ret
SFX_Cry00_1_Ch6::
	sound_ret
SFX_Cry00_2_Ch6::
	sound_ret
SFX_Cry00_3_Ch6::
	sound_ret
SFX_Cry00_1_Ch8::
	sound_ret
SFX_Cry00_2_Ch8::
	sound_ret
SFX_Cry00_3_Ch8::
	sound_ret

; from audio/sfx/cry01.asm
SFX_Cry01_1_Ch5::
	sound_ret
SFX_Cry01_2_Ch5::
	sound_ret
SFX_Cry01_3_Ch5::
	sound_ret
SFX_Cry01_1_Ch6::
	sound_ret
SFX_Cry01_2_Ch6::
	sound_ret
SFX_Cry01_3_Ch6::
	sound_ret
SFX_Cry01_1_Ch8::
	sound_ret
SFX_Cry01_2_Ch8::
	sound_ret
SFX_Cry01_3_Ch8::
	sound_ret

; from audio/sfx/cry02.asm
SFX_Cry02_1_Ch5::
	sound_ret
SFX_Cry02_2_Ch5::
	sound_ret
SFX_Cry02_3_Ch5::
	sound_ret
SFX_Cry02_1_Ch6::
	sound_ret
SFX_Cry02_2_Ch6::
	sound_ret
SFX_Cry02_3_Ch6::
	sound_ret
SFX_Cry02_1_Ch8::
	sound_ret
SFX_Cry02_2_Ch8::
	sound_ret
SFX_Cry02_3_Ch8::
	sound_ret

; from audio/sfx/cry03.asm
SFX_Cry03_1_Ch5::
	sound_ret
SFX_Cry03_2_Ch5::
	sound_ret
SFX_Cry03_3_Ch5::
	sound_ret
SFX_Cry03_1_Ch6::
	sound_ret
SFX_Cry03_2_Ch6::
	sound_ret
SFX_Cry03_3_Ch6::
	sound_ret
SFX_Cry03_1_Ch8::
	sound_ret
SFX_Cry03_2_Ch8::
	sound_ret
SFX_Cry03_3_Ch8::
	sound_ret

; from audio/sfx/cry04.asm
SFX_Cry04_1_Ch5::
	sound_ret
SFX_Cry04_2_Ch5::
	sound_ret
SFX_Cry04_3_Ch5::
	sound_ret
SFX_Cry04_1_Ch6::
	sound_ret
SFX_Cry04_2_Ch6::
	sound_ret
SFX_Cry04_3_Ch6::
	sound_ret
SFX_Cry04_1_Ch8::
	sound_ret
SFX_Cry04_2_Ch8::
	sound_ret
SFX_Cry04_3_Ch8::
	sound_ret

; from audio/sfx/cry05.asm
SFX_Cry05_1_Ch5::
	sound_ret
SFX_Cry05_2_Ch5::
	sound_ret
SFX_Cry05_3_Ch5::
	sound_ret
SFX_Cry05_1_Ch6::
	sound_ret
SFX_Cry05_2_Ch6::
	sound_ret
SFX_Cry05_3_Ch6::
	sound_ret
SFX_Cry05_1_Ch8::
	sound_ret
SFX_Cry05_2_Ch8::
	sound_ret
SFX_Cry05_3_Ch8::
	sound_ret

; from audio/sfx/cry06.asm
SFX_Cry06_1_Ch5::
	sound_ret
SFX_Cry06_2_Ch5::
	sound_ret
SFX_Cry06_3_Ch5::
	sound_ret
SFX_Cry06_1_Ch6::
	sound_ret
SFX_Cry06_2_Ch6::
	sound_ret
SFX_Cry06_3_Ch6::
	sound_ret
SFX_Cry06_1_Ch8::
	sound_ret
SFX_Cry06_2_Ch8::
	sound_ret
SFX_Cry06_3_Ch8::
	sound_ret

; from audio/sfx/cry07.asm
SFX_Cry07_1_Ch5::
	sound_ret
SFX_Cry07_2_Ch5::
	sound_ret
SFX_Cry07_3_Ch5::
	sound_ret
SFX_Cry07_1_Ch6::
	sound_ret
SFX_Cry07_2_Ch6::
	sound_ret
SFX_Cry07_3_Ch6::
	sound_ret
SFX_Cry07_1_Ch8::
	sound_ret
SFX_Cry07_2_Ch8::
	sound_ret
SFX_Cry07_3_Ch8::
	sound_ret

; from audio/sfx/cry08.asm
SFX_Cry08_1_Ch5::
	sound_ret
SFX_Cry08_2_Ch5::
	sound_ret
SFX_Cry08_3_Ch5::
	sound_ret
SFX_Cry08_1_Ch6::
	sound_ret
SFX_Cry08_2_Ch6::
	sound_ret
SFX_Cry08_3_Ch6::
	sound_ret
SFX_Cry08_1_Ch8::
	sound_ret
SFX_Cry08_2_Ch8::
	sound_ret
SFX_Cry08_3_Ch8::
	sound_ret

; from audio/sfx/cry09.asm
SFX_Cry09_1_Ch5::
	sound_ret
SFX_Cry09_2_Ch5::
	sound_ret
SFX_Cry09_3_Ch5::
	sound_ret
SFX_Cry09_1_Ch6::
	sound_ret
SFX_Cry09_2_Ch6::
	sound_ret
SFX_Cry09_3_Ch6::
	sound_ret
SFX_Cry09_1_Ch8::
	sound_ret
SFX_Cry09_2_Ch8::
	sound_ret
SFX_Cry09_3_Ch8::
	sound_ret

; from audio/sfx/cry0a.asm
SFX_Cry0A_1_Ch5::
	sound_ret
SFX_Cry0A_2_Ch5::
	sound_ret
SFX_Cry0A_3_Ch5::
	sound_ret
SFX_Cry0A_1_Ch6::
	sound_ret
SFX_Cry0A_2_Ch6::
	sound_ret
SFX_Cry0A_3_Ch6::
	sound_ret
SFX_Cry0A_1_Ch8::
	sound_ret
SFX_Cry0A_2_Ch8::
	sound_ret
SFX_Cry0A_3_Ch8::
	sound_ret

; from audio/sfx/cry0b.asm
SFX_Cry0B_1_Ch5::
	sound_ret
SFX_Cry0B_2_Ch5::
	sound_ret
SFX_Cry0B_3_Ch5::
	sound_ret
SFX_Cry0B_1_Ch6::
	sound_ret
SFX_Cry0B_2_Ch6::
	sound_ret
SFX_Cry0B_3_Ch6::
	sound_ret
SFX_Cry0B_1_Ch8::
	sound_ret
SFX_Cry0B_2_Ch8::
	sound_ret
SFX_Cry0B_3_Ch8::
	sound_ret

; from audio/sfx/cry0c.asm
SFX_Cry0C_1_Ch5::
	sound_ret
SFX_Cry0C_2_Ch5::
	sound_ret
SFX_Cry0C_3_Ch5::
	sound_ret
SFX_Cry0C_1_Ch6::
	sound_ret
SFX_Cry0C_2_Ch6::
	sound_ret
SFX_Cry0C_3_Ch6::
	sound_ret
SFX_Cry0C_1_Ch8::
	sound_ret
SFX_Cry0C_2_Ch8::
	sound_ret
SFX_Cry0C_3_Ch8::
	sound_ret

; from audio/sfx/cry0d.asm
SFX_Cry0D_1_Ch5::
	sound_ret
SFX_Cry0D_2_Ch5::
	sound_ret
SFX_Cry0D_3_Ch5::
	sound_ret
SFX_Cry0D_1_Ch6::
	sound_ret
SFX_Cry0D_2_Ch6::
	sound_ret
SFX_Cry0D_3_Ch6::
	sound_ret
SFX_Cry0D_1_Ch8::
	sound_ret
SFX_Cry0D_2_Ch8::
	sound_ret
SFX_Cry0D_3_Ch8::
	sound_ret

; from audio/sfx/cry0e.asm
SFX_Cry0E_1_Ch5::
	sound_ret
SFX_Cry0E_2_Ch5::
	sound_ret
SFX_Cry0E_3_Ch5::
	sound_ret
SFX_Cry0E_1_Ch6::
	sound_ret
SFX_Cry0E_2_Ch6::
	sound_ret
SFX_Cry0E_3_Ch6::
	sound_ret
SFX_Cry0E_1_Ch8::
	sound_ret
SFX_Cry0E_2_Ch8::
	sound_ret
SFX_Cry0E_3_Ch8::
	sound_ret

; from audio/sfx/cry0f.asm
SFX_Cry0F_1_Ch5::
	sound_ret
SFX_Cry0F_2_Ch5::
	sound_ret
SFX_Cry0F_3_Ch5::
	sound_ret
SFX_Cry0F_1_Ch6::
	sound_ret
SFX_Cry0F_2_Ch6::
	sound_ret
SFX_Cry0F_3_Ch6::
	sound_ret
SFX_Cry0F_1_Ch8::
	sound_ret
SFX_Cry0F_2_Ch8::
	sound_ret
SFX_Cry0F_3_Ch8::
	sound_ret

; from audio/sfx/cry10.asm
SFX_Cry10_1_Ch5::
	sound_ret
SFX_Cry10_2_Ch5::
	sound_ret
SFX_Cry10_3_Ch5::
	sound_ret
SFX_Cry10_1_Ch6::
	sound_ret
SFX_Cry10_2_Ch6::
	sound_ret
SFX_Cry10_3_Ch6::
	sound_ret
SFX_Cry10_1_Ch8::
	sound_ret
SFX_Cry10_2_Ch8::
	sound_ret
SFX_Cry10_3_Ch8::
	sound_ret

; from audio/sfx/cry11.asm
SFX_Cry11_1_Ch5::
	sound_ret
SFX_Cry11_2_Ch5::
	sound_ret
SFX_Cry11_3_Ch5::
	sound_ret
SFX_Cry11_1_Ch6::
	sound_ret
SFX_Cry11_2_Ch6::
	sound_ret
SFX_Cry11_3_Ch6::
	sound_ret
SFX_Cry11_1_Ch8::
	sound_ret
SFX_Cry11_2_Ch8::
	sound_ret
SFX_Cry11_3_Ch8::
	sound_ret

; from audio/sfx/cry12.asm
SFX_Cry12_1_Ch5::
	sound_ret
SFX_Cry12_2_Ch5::
	sound_ret
SFX_Cry12_3_Ch5::
	sound_ret
SFX_Cry12_1_Ch6::
	sound_ret
SFX_Cry12_2_Ch6::
	sound_ret
SFX_Cry12_3_Ch6::
	sound_ret
SFX_Cry12_1_Ch8::
	sound_ret
SFX_Cry12_2_Ch8::
	sound_ret
SFX_Cry12_3_Ch8::
	sound_ret

; from audio/sfx/cry13.asm
SFX_Cry13_1_Ch5::
	sound_ret
SFX_Cry13_2_Ch5::
	sound_ret
SFX_Cry13_3_Ch5::
	sound_ret
SFX_Cry13_1_Ch6::
	sound_ret
SFX_Cry13_2_Ch6::
	sound_ret
SFX_Cry13_3_Ch6::
	sound_ret
SFX_Cry13_1_Ch8::
	sound_ret
SFX_Cry13_2_Ch8::
	sound_ret
SFX_Cry13_3_Ch8::
	sound_ret

; from audio/sfx/cry14.asm
SFX_Cry14_1_Ch5::
	sound_ret
SFX_Cry14_2_Ch5::
	sound_ret
SFX_Cry14_3_Ch5::
	sound_ret
SFX_Cry14_1_Ch6::
	sound_ret
SFX_Cry14_2_Ch6::
	sound_ret
SFX_Cry14_3_Ch6::
	sound_ret
SFX_Cry14_1_Ch8::
	sound_ret
SFX_Cry14_2_Ch8::
	sound_ret
SFX_Cry14_3_Ch8::
	sound_ret

; from audio/sfx/cry15.asm
SFX_Cry15_1_Ch5::
	sound_ret
SFX_Cry15_2_Ch5::
	sound_ret
SFX_Cry15_3_Ch5::
	sound_ret
SFX_Cry15_1_Ch6::
	sound_ret
SFX_Cry15_2_Ch6::
	sound_ret
SFX_Cry15_3_Ch6::
	sound_ret
SFX_Cry15_1_Ch8::
	sound_ret
SFX_Cry15_2_Ch8::
	sound_ret
SFX_Cry15_3_Ch8::
	sound_ret

; from audio/sfx/cry16.asm
SFX_Cry16_1_Ch5::
	sound_ret
SFX_Cry16_2_Ch5::
	sound_ret
SFX_Cry16_3_Ch5::
	sound_ret
SFX_Cry16_1_Ch6::
	sound_ret
SFX_Cry16_2_Ch6::
	sound_ret
SFX_Cry16_3_Ch6::
	sound_ret
SFX_Cry16_1_Ch8::
	sound_ret
SFX_Cry16_2_Ch8::
	sound_ret
SFX_Cry16_3_Ch8::
	sound_ret

; from audio/sfx/cry17.asm
SFX_Cry17_1_Ch5::
	sound_ret
SFX_Cry17_2_Ch5::
	sound_ret
SFX_Cry17_3_Ch5::
	sound_ret
SFX_Cry17_1_Ch6::
	sound_ret
SFX_Cry17_2_Ch6::
	sound_ret
SFX_Cry17_3_Ch6::
	sound_ret
SFX_Cry17_1_Ch8::
	sound_ret
SFX_Cry17_2_Ch8::
	sound_ret
SFX_Cry17_3_Ch8::
	sound_ret

; from audio/sfx/cry18.asm
SFX_Cry18_1_Ch5::
	sound_ret
SFX_Cry18_2_Ch5::
	sound_ret
SFX_Cry18_3_Ch5::
	sound_ret
SFX_Cry18_1_Ch6::
	sound_ret
SFX_Cry18_2_Ch6::
	sound_ret
SFX_Cry18_3_Ch6::
	sound_ret
SFX_Cry18_1_Ch8::
	sound_ret
SFX_Cry18_2_Ch8::
	sound_ret
SFX_Cry18_3_Ch8::
	sound_ret

; from audio/sfx/cry19.asm
SFX_Cry19_1_Ch5::
	sound_ret
SFX_Cry19_2_Ch5::
	sound_ret
SFX_Cry19_3_Ch5::
	sound_ret
SFX_Cry19_1_Ch6::
	sound_ret
SFX_Cry19_2_Ch6::
	sound_ret
SFX_Cry19_3_Ch6::
	sound_ret
SFX_Cry19_1_Ch8::
	sound_ret
SFX_Cry19_2_Ch8::
	sound_ret
SFX_Cry19_3_Ch8::
	sound_ret

; from audio/sfx/cry1a.asm
SFX_Cry1A_1_Ch5::
	sound_ret
SFX_Cry1A_2_Ch5::
	sound_ret
SFX_Cry1A_3_Ch5::
	sound_ret
SFX_Cry1A_1_Ch6::
	sound_ret
SFX_Cry1A_2_Ch6::
	sound_ret
SFX_Cry1A_3_Ch6::
	sound_ret
SFX_Cry1A_1_Ch8::
	sound_ret
SFX_Cry1A_2_Ch8::
	sound_ret
SFX_Cry1A_3_Ch8::
	sound_ret

; from audio/sfx/cry1b.asm
SFX_Cry1B_1_Ch5::
	sound_ret
SFX_Cry1B_2_Ch5::
	sound_ret
SFX_Cry1B_3_Ch5::
	sound_ret
SFX_Cry1B_1_Ch6::
	sound_ret
SFX_Cry1B_2_Ch6::
	sound_ret
SFX_Cry1B_3_Ch6::
	sound_ret
SFX_Cry1B_1_Ch8::
	sound_ret
SFX_Cry1B_2_Ch8::
	sound_ret
SFX_Cry1B_3_Ch8::
	sound_ret

; from audio/sfx/cry1c.asm
SFX_Cry1C_1_Ch5::
	sound_ret
SFX_Cry1C_2_Ch5::
	sound_ret
SFX_Cry1C_3_Ch5::
	sound_ret
SFX_Cry1C_1_Ch6::
	sound_ret
SFX_Cry1C_2_Ch6::
	sound_ret
SFX_Cry1C_3_Ch6::
	sound_ret
SFX_Cry1C_1_Ch8::
	sound_ret
SFX_Cry1C_2_Ch8::
	sound_ret
SFX_Cry1C_3_Ch8::
	sound_ret

; from audio/sfx/cry1d.asm
SFX_Cry1D_1_Ch5::
	sound_ret
SFX_Cry1D_2_Ch5::
	sound_ret
SFX_Cry1D_3_Ch5::
	sound_ret
SFX_Cry1D_1_Ch6::
	sound_ret
SFX_Cry1D_2_Ch6::
	sound_ret
SFX_Cry1D_3_Ch6::
	sound_ret
SFX_Cry1D_1_Ch8::
	sound_ret
SFX_Cry1D_2_Ch8::
	sound_ret
SFX_Cry1D_3_Ch8::
	sound_ret

; from audio/sfx/cry1e.asm
SFX_Cry1E_1_Ch5::
	sound_ret
SFX_Cry1E_2_Ch5::
	sound_ret
SFX_Cry1E_3_Ch5::
	sound_ret
SFX_Cry1E_1_Ch6::
	sound_ret
SFX_Cry1E_2_Ch6::
	sound_ret
SFX_Cry1E_3_Ch6::
	sound_ret
SFX_Cry1E_1_Ch8::
	sound_ret
SFX_Cry1E_2_Ch8::
	sound_ret
SFX_Cry1E_3_Ch8::
	sound_ret

; from audio/sfx/cry1f.asm
SFX_Cry1F_1_Ch5::
	sound_ret
SFX_Cry1F_2_Ch5::
	sound_ret
SFX_Cry1F_3_Ch5::
	sound_ret
SFX_Cry1F_1_Ch6::
	sound_ret
SFX_Cry1F_2_Ch6::
	sound_ret
SFX_Cry1F_3_Ch6::
	sound_ret
SFX_Cry1F_1_Ch8::
	sound_ret
SFX_Cry1F_2_Ch8::
	sound_ret
SFX_Cry1F_3_Ch8::
	sound_ret

; from audio/sfx/cry20.asm
SFX_Cry20_1_Ch5::
	sound_ret
SFX_Cry20_2_Ch5::
	sound_ret
SFX_Cry20_3_Ch5::
	sound_ret
SFX_Cry20_1_Ch6::
	sound_ret
SFX_Cry20_2_Ch6::
	sound_ret
SFX_Cry20_3_Ch6::
	sound_ret
SFX_Cry20_1_Ch8::
	sound_ret
SFX_Cry20_2_Ch8::
	sound_ret
SFX_Cry20_3_Ch8::
	sound_ret

; from audio/sfx/cry21.asm
SFX_Cry21_1_Ch5::
	sound_ret
SFX_Cry21_2_Ch5::
	sound_ret
SFX_Cry21_3_Ch5::
	sound_ret
SFX_Cry21_1_Ch6::
	sound_ret
SFX_Cry21_2_Ch6::
	sound_ret
SFX_Cry21_3_Ch6::
	sound_ret
SFX_Cry21_1_Ch8::
	sound_ret
SFX_Cry21_2_Ch8::
	sound_ret
SFX_Cry21_3_Ch8::
	sound_ret

; from audio/sfx/cry22.asm
SFX_Cry22_1_Ch5::
	sound_ret
SFX_Cry22_2_Ch5::
	sound_ret
SFX_Cry22_3_Ch5::
	sound_ret
SFX_Cry22_1_Ch6::
	sound_ret
SFX_Cry22_2_Ch6::
	sound_ret
SFX_Cry22_3_Ch6::
	sound_ret
SFX_Cry22_1_Ch8::
	sound_ret
SFX_Cry22_2_Ch8::
	sound_ret
SFX_Cry22_3_Ch8::
	sound_ret

; from audio/sfx/cry23.asm
SFX_Cry23_1_Ch5::
	sound_ret
SFX_Cry23_2_Ch5::
	sound_ret
SFX_Cry23_3_Ch5::
	sound_ret
SFX_Cry23_1_Ch6::
	sound_ret
SFX_Cry23_2_Ch6::
	sound_ret
SFX_Cry23_3_Ch6::
	sound_ret
SFX_Cry23_1_Ch8::
	sound_ret
SFX_Cry23_2_Ch8::
	sound_ret
SFX_Cry23_3_Ch8::
	sound_ret

; from audio/sfx/cry24.asm
SFX_Cry24_1_Ch5::
	sound_ret
SFX_Cry24_2_Ch5::
	sound_ret
SFX_Cry24_3_Ch5::
	sound_ret
SFX_Cry24_1_Ch6::
	sound_ret
SFX_Cry24_2_Ch6::
	sound_ret
SFX_Cry24_3_Ch6::
	sound_ret
SFX_Cry24_1_Ch8::
	sound_ret
SFX_Cry24_2_Ch8::
	sound_ret
SFX_Cry24_3_Ch8::
	sound_ret

; from audio/sfx/cry25.asm
SFX_Cry25_1_Ch5::
	sound_ret
SFX_Cry25_2_Ch5::
	sound_ret
SFX_Cry25_3_Ch5::
	sound_ret
SFX_Cry25_1_Ch6::
	sound_ret
SFX_Cry25_2_Ch6::
	sound_ret
SFX_Cry25_3_Ch6::
	sound_ret
SFX_Cry25_1_Ch8::
	sound_ret
SFX_Cry25_2_Ch8::
	sound_ret
SFX_Cry25_3_Ch8::
	sound_ret

; from audio/sfx/cut.asm
SFX_Cut_1_Ch8::
	sound_ret
SFX_Cut_2_Ch8::
	sound_ret
SFX_Cut_3_Ch8::
	sound_ret

; from audio/sfx/damage.asm
SFX_Damage_Ch8::
	sound_ret

; from audio/sfx/denied.asm
SFX_Denied_1_Ch5::
	sound_ret
SFX_Denied_2_Ch5::
	sound_ret
SFX_Denied_3_Ch5::
	sound_ret
SFX_Denied_1_Ch6::
	sound_ret
SFX_Denied_2_Ch6::
	sound_ret
SFX_Denied_3_Ch6::
	sound_ret

; from audio/sfx/dex_page_added.asm
SFX_Dex_Page_Added_Ch5::
	sound_ret
SFX_Dex_Page_Added_Ch6::
	sound_ret

; from audio/sfx/doubleslap.asm
SFX_Doubleslap_Ch8::
	sound_ret

; from audio/sfx/enter_pc.asm
SFX_Enter_PC_1_Ch5::
	sound_ret
SFX_Enter_PC_2_Ch5::
	sound_ret
SFX_Enter_PC_3_Ch5::
	sound_ret

; from audio/sfx/faint_fall.asm
SFX_Faint_Fall_Ch5::
	sound_ret

; from audio/sfx/faint_thud.asm
SFX_Faint_Thud_Ch5::
	sound_ret
SFX_Faint_Thud_Ch8::
	sound_ret

; from audio/sfx/fly.asm
SFX_Fly_1_Ch8::
	sound_ret
SFX_Fly_2_Ch8::
	sound_ret
SFX_Fly_3_Ch8::
	sound_ret

; from audio/sfx/get_item1.asm
SFX_Get_Item1_1_Ch5::
	sound_ret
SFX_Get_Item1_2_Ch5::
	sound_ret
SFX_Get_Item1_3_Ch5::
	sound_ret
SFX_Get_Item1_1_Ch6::
	sound_ret
SFX_Get_Item1_2_Ch6::
	sound_ret
SFX_Get_Item1_3_Ch6::
	sound_ret
SFX_Get_Item1_1_Ch7::
	sound_ret
SFX_Get_Item1_2_Ch7::
	sound_ret
SFX_Get_Item1_3_Ch7::
	sound_ret

; from audio/sfx/get_item2.asm
SFX_Get_Item2_1_Ch5::
	sound_ret
SFX_Get_Item2_2_Ch5::
	sound_ret
SFX_Get_Item2_3_Ch5::
	sound_ret
SFX_Get_Item2_1_Ch6::
	sound_ret
SFX_Get_Item2_2_Ch6::
	sound_ret
SFX_Get_Item2_3_Ch6::
	sound_ret
SFX_Get_Item2_1_Ch7::
	sound_ret
SFX_Get_Item2_2_Ch7::
	sound_ret
SFX_Get_Item2_3_Ch7::
	sound_ret

; from audio/sfx/get_key_item.asm
SFX_Get_Key_Item_1_Ch5::
	sound_ret
SFX_Get_Key_Item_2_Ch5::
	sound_ret
SFX_Get_Key_Item_3_Ch5::
	sound_ret
SFX_Get_Key_Item_1_Ch6::
	sound_ret
SFX_Get_Key_Item_2_Ch6::
	sound_ret
SFX_Get_Key_Item_3_Ch6::
	sound_ret
SFX_Get_Key_Item_1_Ch7::
	sound_ret
SFX_Get_Key_Item_2_Ch7::
	sound_ret
SFX_Get_Key_Item_3_Ch7::
	sound_ret

; from audio/sfx/go_inside.asm
SFX_Go_Inside_1_Ch8::
	sound_ret
SFX_Go_Inside_2_Ch8::
	sound_ret
SFX_Go_Inside_3_Ch8::
	sound_ret

; from audio/sfx/go_outside.asm
SFX_Go_Outside_1_Ch8::
	sound_ret
SFX_Go_Outside_2_Ch8::
	sound_ret
SFX_Go_Outside_3_Ch8::
	sound_ret

; from audio/sfx/heal_ailment.asm
SFX_Heal_Ailment_1_Ch5::
	sound_ret
SFX_Heal_Ailment_2_Ch5::
	sound_ret
SFX_Heal_Ailment_3_Ch5::
	sound_ret

; from audio/sfx/heal_hp.asm
SFX_Heal_HP_1_Ch5::
	sound_ret
SFX_Heal_HP_2_Ch5::
	sound_ret
SFX_Heal_HP_3_Ch5::
	sound_ret

; from audio/sfx/healing_machine.asm
SFX_Healing_Machine_1_Ch5::
	sound_ret
SFX_Healing_Machine_2_Ch5::
	sound_ret
SFX_Healing_Machine_3_Ch5::
	sound_ret

; from audio/sfx/horn_drill.asm
SFX_Horn_Drill_Ch8::
	sound_ret

; from audio/sfx/intro_crash.asm
SFX_Intro_Crash_Ch8::
	sound_ret

; from audio/sfx/intro_hip.asm
SFX_Intro_Hip_Ch8::
	sound_ret

; from audio/sfx/intro_hop.asm
SFX_Intro_Hop_Ch8::
	sound_ret

; from audio/sfx/intro_lunge.asm
SFX_Intro_Lunge_Ch8::
	sound_ret

; from audio/sfx/intro_raise.asm
SFX_Intro_Raise_Ch8::
	sound_ret

; from audio/sfx/intro_whoosh.asm
SFX_Intro_Whoosh_Ch8::
	sound_ret

; from audio/sfx/ledge.asm
SFX_Ledge_1_Ch5::
	sound_ret
SFX_Ledge_2_Ch5::
	sound_ret
SFX_Ledge_3_Ch5::
	sound_ret

; from audio/sfx/level_up.asm
SFX_Level_Up_Ch5::
	sound_ret
SFX_Level_Up_Ch6::
	sound_ret
SFX_Level_Up_Ch7::
	sound_ret

; from audio/sfx/not_very_effective.asm
SFX_Not_Very_Effective_Ch8::
	sound_ret

; from audio/sfx/peck.asm
SFX_Peck_Ch8::
	sound_ret

; from audio/sfx/poisoned.asm
SFX_Poisoned_1_Ch5::
	sound_ret
SFX_Poisoned_2_Ch5::
	sound_ret
SFX_Poisoned_3_Ch5::
	sound_ret

; from audio/sfx/pokedex_rating.asm
SFX_Pokedex_Rating_1_Ch5::
	sound_ret
SFX_Pokedex_Rating_2_Ch5::
	sound_ret
SFX_Pokedex_Rating_3_Ch5::
	sound_ret
SFX_Pokedex_Rating_1_Ch6::
	sound_ret
SFX_Pokedex_Rating_2_Ch6::
	sound_ret
SFX_Pokedex_Rating_3_Ch6::
	sound_ret
SFX_Pokedex_Rating_1_Ch7::
	sound_ret
SFX_Pokedex_Rating_2_Ch7::
	sound_ret
SFX_Pokedex_Rating_3_Ch7::
	sound_ret

; from audio/sfx/pokeflute.asm
SFX_Pokeflute_Ch3::
	sound_ret

; from audio/sfx/pokeflute_ch5_ch6.asm
SFX_Pokeflute_Ch5::
	sound_ret
SFX_Pokeflute_Ch6::
	sound_ret

; from audio/sfx/pokeflute_ch7.asm
SFX_Pokeflute_Ch7::
	sound_ret

; from audio/sfx/pound.asm
SFX_Pound_Ch8::
	sound_ret

; from audio/sfx/press_ab.asm
SFX_Press_AB_1_Ch5::
	sound_ret
SFX_Press_AB_2_Ch5::
	sound_ret
SFX_Press_AB_3_Ch5::
	sound_ret

; from audio/sfx/psybeam.asm
SFX_Psybeam_Ch5::
	sound_ret
SFX_Psybeam_Ch6::
	sound_ret
SFX_Psybeam_Ch8::
	sound_ret

; from audio/sfx/psychic_m.asm
SFX_Psychic_M_Ch5::
	sound_ret
SFX_Psychic_M_Ch6::
	sound_ret
SFX_Psychic_M_Ch8::
	sound_ret

; from audio/sfx/purchase.asm
SFX_Purchase_1_Ch5::
	sound_ret
SFX_Purchase_2_Ch5::
	sound_ret
SFX_Purchase_3_Ch5::
	sound_ret
SFX_Purchase_1_Ch6::
	sound_ret
SFX_Purchase_2_Ch6::
	sound_ret
SFX_Purchase_3_Ch6::
	sound_ret

; from audio/sfx/push_boulder.asm
SFX_Push_Boulder_1_Ch8::
	sound_ret
SFX_Push_Boulder_2_Ch8::
	sound_ret
SFX_Push_Boulder_3_Ch8::
	sound_ret

; from audio/sfx/run.asm
SFX_Run_Ch8::
	sound_ret

; from audio/sfx/safari_zone_pa.asm
SFX_Safari_Zone_PA_Ch5::
	sound_ret

; from audio/sfx/save.asm
SFX_Save_1_Ch5::
	sound_ret
SFX_Save_2_Ch5::
	sound_ret
SFX_Save_3_Ch5::
	sound_ret
SFX_Save_1_Ch6::
	sound_ret
SFX_Save_2_Ch6::
	sound_ret
SFX_Save_3_Ch6::
	sound_ret

; from audio/sfx/shooting_star.asm
SFX_Shooting_Star_Ch5::
	sound_ret

; from audio/sfx/shrink.asm
SFX_Shrink_1_Ch5::
	sound_ret
SFX_Shrink_2_Ch5::
	sound_ret
SFX_Shrink_3_Ch5::
	sound_ret

; from audio/sfx/slots_new_spin.asm
SFX_Slots_New_Spin_Ch5::
	sound_ret
SFX_Slots_New_Spin_Ch6::
	sound_ret

; from audio/sfx/slots_reward.asm
SFX_Slots_Reward_Ch5::
	sound_ret

; from audio/sfx/slots_stop_wheel.asm
SFX_Slots_Stop_Wheel_Ch5::
	sound_ret

; from audio/sfx/ss_anne_horn.asm
SFX_SS_Anne_Horn_1_Ch5::
	sound_ret
SFX_SS_Anne_Horn_2_Ch5::
	sound_ret
SFX_SS_Anne_Horn_3_Ch5::
	sound_ret
SFX_SS_Anne_Horn_1_Ch6::
	sound_ret
SFX_SS_Anne_Horn_2_Ch6::
	sound_ret
SFX_SS_Anne_Horn_3_Ch6::
	sound_ret

; from audio/sfx/start_menu.asm
SFX_Start_Menu_1_Ch8::
	sound_ret
SFX_Start_Menu_2_Ch8::
	sound_ret
SFX_Start_Menu_3_Ch8::
	sound_ret

; from audio/sfx/super_effective.asm
SFX_Super_Effective_Ch8::
	sound_ret

; from audio/sfx/swap.asm
SFX_Swap_1_Ch5::
	sound_ret
SFX_Swap_2_Ch5::
	sound_ret
SFX_Swap_3_Ch5::
	sound_ret
SFX_Swap_1_Ch6::
	sound_ret
SFX_Swap_2_Ch6::
	sound_ret
SFX_Swap_3_Ch6::
	sound_ret

; from audio/sfx/switch.asm
SFX_Switch_1_Ch5::
	sound_ret
SFX_Switch_2_Ch5::
	sound_ret
SFX_Switch_3_Ch5::
	sound_ret

; from audio/sfx/teleport_enter1.asm
SFX_Teleport_Enter1_1_Ch5::
	sound_ret
SFX_Teleport_Enter1_2_Ch5::
	sound_ret
SFX_Teleport_Enter1_3_Ch5::
	sound_ret

; from audio/sfx/teleport_enter2.asm
SFX_Teleport_Enter2_1_Ch8::
	sound_ret
SFX_Teleport_Enter2_2_Ch8::
	sound_ret
SFX_Teleport_Enter2_3_Ch8::
	sound_ret

; from audio/sfx/teleport_exit1.asm
SFX_Teleport_Exit1_1_Ch5::
	sound_ret
SFX_Teleport_Exit1_2_Ch5::
	sound_ret
SFX_Teleport_Exit1_3_Ch5::
	sound_ret

; from audio/sfx/teleport_exit2.asm
SFX_Teleport_Exit2_1_Ch5::
	sound_ret
SFX_Teleport_Exit2_2_Ch5::
	sound_ret
SFX_Teleport_Exit2_3_Ch5::
	sound_ret

; from audio/sfx/tink.asm
SFX_Tink_1_Ch5::
	sound_ret
SFX_Tink_2_Ch5::
	sound_ret
SFX_Tink_3_Ch5::
	sound_ret

; from audio/sfx/trade_machine.asm
SFX_Trade_Machine_1_Ch5::
	sound_ret
SFX_Trade_Machine_2_Ch5::
	sound_ret
SFX_Trade_Machine_3_Ch5::
	sound_ret

; from audio/sfx/trainer_appeared.asm
SFX_Trainer_Appeared_Ch5::
	sound_ret

; from audio/sfx/turn_off_pc.asm
SFX_Turn_Off_PC_1_Ch5::
	sound_ret
SFX_Turn_Off_PC_2_Ch5::
	sound_ret
SFX_Turn_Off_PC_3_Ch5::
	sound_ret

; from audio/sfx/turn_on_pc.asm
SFX_Turn_On_PC_1_Ch5::
	sound_ret
SFX_Turn_On_PC_2_Ch5::
	sound_ret
SFX_Turn_On_PC_3_Ch5::
	sound_ret

; from audio/sfx/unused_cry.asm
SFX_UnusedCry_1_Ch5::
	sound_ret
SFX_UnusedCry_2_Ch5::
	sound_ret
SFX_UnusedCry_3_Ch5::
	sound_ret
SFX_UnusedCry_1_Ch6::
	sound_ret
SFX_UnusedCry_2_Ch6::
	sound_ret
SFX_UnusedCry_3_Ch6::
	sound_ret
SFX_UnusedCry_1_Ch8::
	sound_ret
SFX_UnusedCry_2_Ch8::
	sound_ret
SFX_UnusedCry_3_Ch8::
	sound_ret

; from audio/sfx/unused_fanfare.asm
SFX_UnusedFanfare_Ch5::
	sound_ret
SFX_UnusedFanfare_Ch6::
	sound_ret
SFX_UnusedFanfare_Ch7::
	sound_ret

; from audio/sfx/vine_whip.asm
SFX_Vine_Whip_Ch8::
	sound_ret

; from audio/sfx/withdraw_deposit.asm
SFX_Withdraw_Deposit_1_Ch5::
	sound_ret
SFX_Withdraw_Deposit_2_Ch5::
	sound_ret
SFX_Withdraw_Deposit_3_Ch5::
	sound_ret
