; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/music/credits.asm
Music_Credits_Ch1::
	sound_ret
Music_Credits_Ch2::
	sound_ret
Music_Credits_Ch3::
	sound_ret
