; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/sfx/get_item1.asm
	audio_eng_channel SFX_Get_Item1, 5
	sound_ret
	audio_eng_channel SFX_Get_Item1, 6
	sound_ret
	audio_eng_channel SFX_Get_Item1, 7
	sound_ret

; from audio/sfx/pokedex_rating.asm
	audio_eng_channel SFX_Pokedex_Rating, 5
	sound_ret
	audio_eng_channel SFX_Pokedex_Rating, 6
	sound_ret
	audio_eng_channel SFX_Pokedex_Rating, 7
	sound_ret

; from audio/sfx/get_item2.asm
	audio_eng_channel SFX_Get_Item2, 5
	sound_ret
	audio_eng_channel SFX_Get_Item2, 6
	sound_ret
	audio_eng_channel SFX_Get_Item2, 7
	sound_ret

; from audio/sfx/get_key_item.asm
	audio_eng_channel SFX_Get_Key_Item, 5
	sound_ret
	audio_eng_channel SFX_Get_Key_Item, 6
	sound_ret
	audio_eng_channel SFX_Get_Key_Item, 7
	sound_ret
