; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/sfx/pokeflute_ch5_ch6.asm
SFX_Pokeflute_Ch5::
	sound_ret
SFX_Pokeflute_Ch6::
	sound_ret

; from audio/sfx/unused_fanfare.asm
SFX_UnusedFanfare_Ch5::
	sound_ret
SFX_UnusedFanfare_Ch6::
	sound_ret
SFX_UnusedFanfare_Ch7::
	sound_ret

; from audio/sfx/level_up.asm
SFX_Level_Up_Ch5::
	sound_ret
SFX_Level_Up_Ch6::
	sound_ret
SFX_Level_Up_Ch7::
	sound_ret

; from audio/sfx/get_item2.asm
	audio_eng_channel SFX_Get_Item2, 5
	sound_ret
	audio_eng_channel SFX_Get_Item2, 6
	sound_ret
	audio_eng_channel SFX_Get_Item2, 7
	sound_ret

; from audio/sfx/caught_mon.asm
SFX_Caught_Mon_Ch5::
	sound_ret
SFX_Caught_Mon_Ch6::
	sound_ret
SFX_Caught_Mon_Ch7::
	sound_ret
