; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/music/bike_riding.asm
Music_BikeRiding_Ch1::
	sound_ret
Music_BikeRiding_Ch2::
	sound_ret
Music_BikeRiding_Ch3::
	sound_ret
Music_BikeRiding_Ch4::
	sound_ret

; from audio/music/dungeon_1.asm
Music_Dungeon1_Ch1::
	sound_ret
Music_Dungeon1_Ch2::
	sound_ret
Music_Dungeon1_Ch3::
	sound_ret
Music_Dungeon1_Ch4::
	sound_ret

; from audio/music/game_corner.asm
Music_GameCorner_Ch1::
	sound_ret
Music_GameCorner_Ch2::
	sound_ret
Music_GameCorner_Ch3::
	sound_ret

; from audio/music/title_screen.asm
Music_TitleScreen_Ch1::
	sound_ret
Music_TitleScreen_Ch2::
	sound_ret
Music_TitleScreen_Ch3::
	sound_ret
Music_TitleScreen_Ch4::
	sound_ret

; from audio/music/dungeon_2.asm
Music_Dungeon2_Ch1::
	sound_ret
Music_Dungeon2_Ch2::
	sound_ret
Music_Dungeon2_Ch3::
	sound_ret
Music_Dungeon2_Ch4::
	sound_ret

; from audio/music/dungeon_3.asm
Music_Dungeon3_Ch1::
	sound_ret
Music_Dungeon3_Ch2::
	sound_ret
Music_Dungeon3_Ch3::
	sound_ret
Music_Dungeon3_Ch4::
	sound_ret

; from audio/music/cinnabar_mansion.asm
Music_CinnabarMansion_Ch1::
	sound_ret
Music_CinnabarMansion_Ch2::
	sound_ret
Music_CinnabarMansion_Ch3::
	sound_ret
Music_CinnabarMansion_Ch4::
	sound_ret

; from audio/music/oaks_lab.asm
Music_OaksLab_Ch1::
	sound_ret
Music_OaksLab_Ch2::
	sound_ret
Music_OaksLab_Ch3::
	sound_ret

; from audio/music/pokemon_tower.asm
Music_PokemonTower_Ch1::
	sound_ret
Music_PokemonTower_Ch2::
	sound_ret
Music_PokemonTower_Ch3::
	sound_ret

; from audio/music/silph_co.asm
Music_SilphCo_Ch1::
	sound_ret
Music_SilphCo_Ch2::
	sound_ret
Music_SilphCo_Ch3::
	sound_ret

; from audio/music/meet_evil_trainer.asm
Music_MeetEvilTrainer_Ch1::
	sound_ret
Music_MeetEvilTrainer_Ch2::
	sound_ret
Music_MeetEvilTrainer_Ch3::
	sound_ret

; from audio/music/meet_female_trainer.asm
Music_MeetFemaleTrainer_Ch1::
	sound_ret
Music_MeetFemaleTrainer_Ch2::
	sound_ret
Music_MeetFemaleTrainer_Ch3::
	sound_ret

; from audio/music/meet_male_trainer.asm
Music_MeetMaleTrainer_Ch1::
	sound_ret
Music_MeetMaleTrainer_Ch2::
	sound_ret
Music_MeetMaleTrainer_Ch3::
	sound_ret

; from audio/music/intro_battle.asm
Music_IntroBattle_Ch1::
	sound_ret
Music_IntroBattle_Ch2::
	sound_ret
Music_IntroBattle_Ch3::
	sound_ret
Music_IntroBattle_Ch4::
	sound_ret

; from audio/music/surfing.asm
Music_Surfing_Ch1::
	sound_ret
Music_Surfing_Ch2::
	sound_ret
Music_Surfing_Ch3::
	sound_ret

; from audio/music/jigglypuff_song.asm
Music_JigglypuffSong_Ch1::
	sound_ret
Music_JigglypuffSong_Ch2::
	sound_ret

; from audio/music/hall_of_fame.asm
Music_HallOfFame_Ch1::
	sound_ret
Music_HallOfFame_Ch2::
	sound_ret
Music_HallOfFame_Ch3::
	sound_ret
