; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/music/gym_leader_battle.asm
Music_GymLeaderBattle_Ch1::
	sound_ret
Music_GymLeaderBattle_Ch2::
	sound_ret
Music_GymLeaderBattle_Ch3::
	sound_ret

; from audio/music/trainer_battle.asm
Music_TrainerBattle_Ch1::
	sound_ret
Music_TrainerBattle_Ch2::
	sound_ret
Music_TrainerBattle_Ch3::
	sound_ret

; from audio/music/wild_battle.asm
Music_WildBattle_Ch1::
	sound_ret
Music_WildBattle_Ch2::
	sound_ret
Music_WildBattle_Ch3::
	sound_ret

; from audio/music/final_battle.asm
Music_FinalBattle_Ch1::
	sound_ret
Music_FinalBattle_Ch2::
	sound_ret
Music_FinalBattle_Ch3::
	sound_ret

; from audio/music/defeated_trainer.asm
Music_DefeatedTrainer_Ch1::
	sound_ret
Music_DefeatedTrainer_Ch2::
	sound_ret
Music_DefeatedTrainer_Ch3::
	sound_ret

; from audio/music/defeated_wild_mon.asm
Music_DefeatedWildMon_Ch1::
	sound_ret
Music_DefeatedWildMon_Ch2::
	sound_ret
Music_DefeatedWildMon_Ch3::
	sound_ret

; from audio/music/defeated_gym_leader.asm
Music_DefeatedGymLeader_Ch1::
	sound_ret
Music_DefeatedGymLeader_Ch2::
	sound_ret
Music_DefeatedGymLeader_Ch3::
	sound_ret
