; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/music/pkmn_healed.asm
Music_PkmnHealed_Ch1::
	sound_ret
Music_PkmnHealed_Ch2::
	sound_ret
Music_PkmnHealed_Ch3::
	sound_ret

; from audio/music/routes_1.asm
Music_Routes1_Ch1::
	sound_ret
Music_Routes1_Ch2::
	sound_ret
Music_Routes1_Ch3::
	sound_ret
Music_Routes1_Ch4::
	sound_ret

; from audio/music/routes_2.asm
Music_Routes2_Ch1::
	sound_ret
Music_Routes2_Ch2::
	sound_ret
Music_Routes2_Ch3::
	sound_ret
Music_Routes2_Ch4::
	sound_ret

; from audio/music/routes_3.asm
Music_Routes3_Ch1::
	sound_ret
Music_Routes3_Ch2::
	sound_ret
Music_Routes3_Ch3::
	sound_ret
Music_Routes3_Ch4::
	sound_ret

; from audio/music/routes_4.asm
Music_Routes4_Ch1::
	sound_ret
Music_Routes4_Ch2::
	sound_ret
Music_Routes4_Ch3::
	sound_ret
Music_Routes4_Ch4::
	sound_ret

; from audio/music/indigo_plateau.asm
Music_IndigoPlateau_Ch1::
	sound_ret
Music_IndigoPlateau_Ch2::
	sound_ret
Music_IndigoPlateau_Ch3::
	sound_ret
Music_IndigoPlateau_Ch4::
	sound_ret

; from audio/music/pallet_town.asm
Music_PalletTown_Ch1::
	sound_ret
Music_PalletTown_Ch2::
	sound_ret
Music_PalletTown_Ch3::
	sound_ret

; from audio/music/unused_song.asm
Music_UnusedSong_Ch1::
	sound_ret
Music_UnusedSong_Ch2::
	sound_ret

; from audio/music/cities_1.asm
Music_Cities1_Ch1_AlternateTempo::
	sound_ret
Music_Cities1_Ch1::
	sound_ret
Music_Cities1_Ch2::
	sound_ret
Music_Cities1_Ch3::
	sound_ret
Music_Cities1_Ch4::
	sound_ret

; from audio/music/museum_guy.asm
Music_MuseumGuy_Ch1::
	sound_ret
Music_MuseumGuy_Ch2::
	sound_ret
Music_MuseumGuy_Ch3::
	sound_ret
Music_MuseumGuy_Ch4::
	sound_ret

; from audio/music/meet_prof_oak.asm
Music_MeetProfOak_Ch1::
	sound_ret
Music_MeetProfOak_Ch2::
	sound_ret
Music_MeetProfOak_Ch3::
	sound_ret

; from audio/music/meet_rival.asm
Music_MeetRival_Ch1_AlternateTempo::
	sound_ret
Music_MeetRival_Ch1::
	sound_ret
Music_MeetRival_Ch1_AlternateStartAndTempo::
	sound_ret
Music_MeetRival_Ch1_AlternateStart::
	sound_ret
Music_MeetRival_Ch2::
	sound_ret
Music_MeetRival_Ch2_AlternateStart::
	sound_ret
Music_MeetRival_Ch3::
	sound_ret
Music_MeetRival_Ch3_AlternateStart::
	sound_ret

; from audio/music/ss_anne.asm
Music_SSAnne_Ch1::
	sound_ret
Music_SSAnne_Ch2::
	sound_ret
Music_SSAnne_Ch3::
	sound_ret

; from audio/music/cities_2.asm
Music_Cities2_Ch1::
	sound_ret
Music_Cities2_Ch2::
	sound_ret
Music_Cities2_Ch3::
	sound_ret

; from audio/music/celadon.asm
Music_Celadon_Ch1::
	sound_ret
Music_Celadon_Ch2::
	sound_ret
Music_Celadon_Ch3::
	sound_ret

; from audio/music/cinnabar.asm
Music_Cinnabar_Ch1::
	sound_ret
Music_Cinnabar_Ch2::
	sound_ret
Music_Cinnabar_Ch3::
	sound_ret

; from audio/music/vermilion.asm
Music_Vermilion_Ch1::
	sound_ret
Music_Vermilion_Ch2::
	sound_ret
Music_Vermilion_Ch3::
	sound_ret
Music_Vermilion_Ch4::
	sound_ret

; from audio/music/lavender.asm
Music_Lavender_Ch1::
	sound_ret
Music_Lavender_Ch2::
	sound_ret
Music_Lavender_Ch3::
	sound_ret
Music_Lavender_Ch4::
	sound_ret

; from audio/music/safari_zone.asm
Music_SafariZone_Ch1::
	sound_ret
Music_SafariZone_Ch2::
	sound_ret
Music_SafariZone_Ch3::
	sound_ret

; from audio/music/gym.asm
Music_Gym_Ch1::
	sound_ret
Music_Gym_Ch2::
	sound_ret
Music_Gym_Ch3::
	sound_ret

; from audio/music/pokecenter.asm
Music_Pokecenter_Ch1::
	sound_ret
Music_Pokecenter_Ch2::
	sound_ret
Music_Pokecenter_Ch3::
	sound_ret
