; Auto-generated by tools/generate_audio_headroom_stubs.py
; Emits silent stubs that preserve global labels/pointers.

; from audio/sfx/start_menu.asm
	audio_eng_channel SFX_Start_Menu, 8
	sound_ret

; from audio/sfx/cut.asm
	audio_eng_channel SFX_Cut, 8
	sound_ret

; from audio/sfx/go_inside.asm
	audio_eng_channel SFX_Go_Inside, 8
	sound_ret

; from audio/sfx/swap.asm
	audio_eng_channel SFX_Swap, 5
	sound_ret
	audio_eng_channel SFX_Swap, 6
	sound_ret

; from audio/sfx/tink.asm
	audio_eng_channel SFX_Tink, 5
	sound_ret

; from audio/sfx/59.asm
	audio_eng_channel SFX_59, 5
	sound_ret
	audio_eng_channel SFX_59, 6
	sound_ret

; from audio/sfx/purchase.asm
	audio_eng_channel SFX_Purchase, 5
	sound_ret
	audio_eng_channel SFX_Purchase, 6
	sound_ret

; from audio/sfx/collision.asm
	audio_eng_channel SFX_Collision, 5
	sound_ret

; from audio/sfx/go_outside.asm
	audio_eng_channel SFX_Go_Outside, 8
	sound_ret

; from audio/sfx/press_ab.asm
	audio_eng_channel SFX_Press_AB, 5
	sound_ret

; from audio/sfx/save.asm
	audio_eng_channel SFX_Save, 5
	sound_ret
	audio_eng_channel SFX_Save, 6
	sound_ret

; from audio/sfx/heal_hp.asm
	audio_eng_channel SFX_Heal_HP, 5
	sound_ret

; from audio/sfx/poisoned.asm
	audio_eng_channel SFX_Poisoned, 5
	sound_ret

; from audio/sfx/heal_ailment.asm
	audio_eng_channel SFX_Heal_Ailment, 5
	sound_ret

; from audio/sfx/trade_machine.asm
	audio_eng_channel SFX_Trade_Machine, 5
	sound_ret

; from audio/sfx/turn_on_pc.asm
	audio_eng_channel SFX_Turn_On_PC, 5
	sound_ret

; from audio/sfx/turn_off_pc.asm
	audio_eng_channel SFX_Turn_Off_PC, 5
	sound_ret

; from audio/sfx/enter_pc.asm
	audio_eng_channel SFX_Enter_PC, 5
	sound_ret

; from audio/sfx/shrink.asm
	audio_eng_channel SFX_Shrink, 5
	sound_ret

; from audio/sfx/switch.asm
	audio_eng_channel SFX_Switch, 5
	sound_ret

; from audio/sfx/healing_machine.asm
	audio_eng_channel SFX_Healing_Machine, 5
	sound_ret

; from audio/sfx/teleport_exit1.asm
	audio_eng_channel SFX_Teleport_Exit1, 5
	sound_ret

; from audio/sfx/teleport_enter1.asm
	audio_eng_channel SFX_Teleport_Enter1, 5
	sound_ret

; from audio/sfx/teleport_exit2.asm
	audio_eng_channel SFX_Teleport_Exit2, 5
	sound_ret

; from audio/sfx/ledge.asm
	audio_eng_channel SFX_Ledge, 5
	sound_ret

; from audio/sfx/teleport_enter2.asm
	audio_eng_channel SFX_Teleport_Enter2, 8
	sound_ret

; from audio/sfx/fly.asm
	audio_eng_channel SFX_Fly, 8
	sound_ret

; from audio/sfx/denied.asm
	audio_eng_channel SFX_Denied, 5
	sound_ret
	audio_eng_channel SFX_Denied, 6
	sound_ret

; from audio/sfx/arrow_tiles.asm
	audio_eng_channel SFX_Arrow_Tiles, 5
	sound_ret

; from audio/sfx/push_boulder.asm
	audio_eng_channel SFX_Push_Boulder, 8
	sound_ret

; from audio/sfx/ss_anne_horn.asm
	audio_eng_channel SFX_SS_Anne_Horn, 5
	sound_ret
	audio_eng_channel SFX_SS_Anne_Horn, 6
	sound_ret

; from audio/sfx/withdraw_deposit.asm
	audio_eng_channel SFX_Withdraw_Deposit, 5
	sound_ret

; from audio/sfx/intro_lunge.asm
SFX_Intro_Lunge_Ch8::
	sound_ret

; from audio/sfx/intro_hip.asm
SFX_Intro_Hip_Ch8::
	sound_ret

; from audio/sfx/intro_hop.asm
SFX_Intro_Hop_Ch8::
	sound_ret

; from audio/sfx/intro_raise.asm
SFX_Intro_Raise_Ch8::
	sound_ret

; from audio/sfx/intro_crash.asm
SFX_Intro_Crash_Ch8::
	sound_ret

; from audio/sfx/intro_whoosh.asm
SFX_Intro_Whoosh_Ch8::
	sound_ret

; from audio/sfx/slots_stop_wheel.asm
SFX_Slots_Stop_Wheel_Ch5::
	sound_ret

; from audio/sfx/slots_reward.asm
SFX_Slots_Reward_Ch5::
	sound_ret

; from audio/sfx/slots_new_spin.asm
SFX_Slots_New_Spin_Ch5::
	sound_ret
SFX_Slots_New_Spin_Ch6::
	sound_ret

; from audio/sfx/shooting_star.asm
SFX_Shooting_Star_Ch5::
	sound_ret

; from audio/sfx/cry00.asm
	audio_eng_channel SFX_Cry00, 5
	sound_ret
	audio_eng_channel SFX_Cry00, 6
	sound_ret
	audio_eng_channel SFX_Cry00, 8
	sound_ret

; from audio/sfx/cry01.asm
	audio_eng_channel SFX_Cry01, 5
	sound_ret
	audio_eng_channel SFX_Cry01, 6
	sound_ret
	audio_eng_channel SFX_Cry01, 8
	sound_ret

; from audio/sfx/cry02.asm
	audio_eng_channel SFX_Cry02, 5
	sound_ret
	audio_eng_channel SFX_Cry02, 6
	sound_ret
	audio_eng_channel SFX_Cry02, 8
	sound_ret

; from audio/sfx/cry03.asm
	audio_eng_channel SFX_Cry03, 5
	sound_ret
	audio_eng_channel SFX_Cry03, 6
	sound_ret
	audio_eng_channel SFX_Cry03, 8
	sound_ret

; from audio/sfx/cry04.asm
	audio_eng_channel SFX_Cry04, 5
	sound_ret
	audio_eng_channel SFX_Cry04, 6
	sound_ret
	audio_eng_channel SFX_Cry04, 8
	sound_ret

; from audio/sfx/cry05.asm
	audio_eng_channel SFX_Cry05, 5
	sound_ret
	audio_eng_channel SFX_Cry05, 6
	sound_ret
	audio_eng_channel SFX_Cry05, 8
	sound_ret

; from audio/sfx/cry06.asm
	audio_eng_channel SFX_Cry06, 5
	sound_ret
	audio_eng_channel SFX_Cry06, 6
	sound_ret
	audio_eng_channel SFX_Cry06, 8
	sound_ret

; from audio/sfx/cry07.asm
	audio_eng_channel SFX_Cry07, 5
	sound_ret
	audio_eng_channel SFX_Cry07, 6
	sound_ret
	audio_eng_channel SFX_Cry07, 8
	sound_ret

; from audio/sfx/cry08.asm
	audio_eng_channel SFX_Cry08, 5
	sound_ret
	audio_eng_channel SFX_Cry08, 6
	sound_ret
	audio_eng_channel SFX_Cry08, 8
	sound_ret

; from audio/sfx/cry09.asm
	audio_eng_channel SFX_Cry09, 5
	sound_ret
	audio_eng_channel SFX_Cry09, 6
	sound_ret
	audio_eng_channel SFX_Cry09, 8
	sound_ret

; from audio/sfx/cry0a.asm
	audio_eng_channel SFX_Cry0A, 5
	sound_ret
	audio_eng_channel SFX_Cry0A, 6
	sound_ret
	audio_eng_channel SFX_Cry0A, 8
	sound_ret

; from audio/sfx/cry0b.asm
	audio_eng_channel SFX_Cry0B, 5
	sound_ret
	audio_eng_channel SFX_Cry0B, 6
	sound_ret
	audio_eng_channel SFX_Cry0B, 8
	sound_ret

; from audio/sfx/cry0c.asm
	audio_eng_channel SFX_Cry0C, 5
	sound_ret
	audio_eng_channel SFX_Cry0C, 6
	sound_ret
	audio_eng_channel SFX_Cry0C, 8
	sound_ret

; from audio/sfx/cry0d.asm
	audio_eng_channel SFX_Cry0D, 5
	sound_ret
	audio_eng_channel SFX_Cry0D, 6
	sound_ret
	audio_eng_channel SFX_Cry0D, 8
	sound_ret

; from audio/sfx/cry0e.asm
	audio_eng_channel SFX_Cry0E, 5
	sound_ret
	audio_eng_channel SFX_Cry0E, 6
	sound_ret
	audio_eng_channel SFX_Cry0E, 8
	sound_ret

; from audio/sfx/cry0f.asm
	audio_eng_channel SFX_Cry0F, 5
	sound_ret
	audio_eng_channel SFX_Cry0F, 6
	sound_ret
	audio_eng_channel SFX_Cry0F, 8
	sound_ret

; from audio/sfx/cry10.asm
	audio_eng_channel SFX_Cry10, 5
	sound_ret
	audio_eng_channel SFX_Cry10, 6
	sound_ret
	audio_eng_channel SFX_Cry10, 8
	sound_ret

; from audio/sfx/cry11.asm
	audio_eng_channel SFX_Cry11, 5
	sound_ret
	audio_eng_channel SFX_Cry11, 6
	sound_ret
	audio_eng_channel SFX_Cry11, 8
	sound_ret

; from audio/sfx/cry12.asm
	audio_eng_channel SFX_Cry12, 5
	sound_ret
	audio_eng_channel SFX_Cry12, 6
	sound_ret
	audio_eng_channel SFX_Cry12, 8
	sound_ret

; from audio/sfx/cry13.asm
	audio_eng_channel SFX_Cry13, 5
	sound_ret
	audio_eng_channel SFX_Cry13, 6
	sound_ret
	audio_eng_channel SFX_Cry13, 8
	sound_ret

; from audio/sfx/cry14.asm
	audio_eng_channel SFX_Cry14, 5
	sound_ret
	audio_eng_channel SFX_Cry14, 6
	sound_ret
	audio_eng_channel SFX_Cry14, 8
	sound_ret

; from audio/sfx/cry15.asm
	audio_eng_channel SFX_Cry15, 5
	sound_ret
	audio_eng_channel SFX_Cry15, 6
	sound_ret
	audio_eng_channel SFX_Cry15, 8
	sound_ret

; from audio/sfx/cry16.asm
	audio_eng_channel SFX_Cry16, 5
	sound_ret
	audio_eng_channel SFX_Cry16, 6
	sound_ret
	audio_eng_channel SFX_Cry16, 8
	sound_ret

; from audio/sfx/cry17.asm
	audio_eng_channel SFX_Cry17, 5
	sound_ret
	audio_eng_channel SFX_Cry17, 6
	sound_ret
	audio_eng_channel SFX_Cry17, 8
	sound_ret

; from audio/sfx/cry18.asm
	audio_eng_channel SFX_Cry18, 5
	sound_ret
	audio_eng_channel SFX_Cry18, 6
	sound_ret
	audio_eng_channel SFX_Cry18, 8
	sound_ret

; from audio/sfx/cry19.asm
	audio_eng_channel SFX_Cry19, 5
	sound_ret
	audio_eng_channel SFX_Cry19, 6
	sound_ret
	audio_eng_channel SFX_Cry19, 8
	sound_ret

; from audio/sfx/cry1a.asm
	audio_eng_channel SFX_Cry1A, 5
	sound_ret
	audio_eng_channel SFX_Cry1A, 6
	sound_ret
	audio_eng_channel SFX_Cry1A, 8
	sound_ret

; from audio/sfx/cry1b.asm
	audio_eng_channel SFX_Cry1B, 5
	sound_ret
	audio_eng_channel SFX_Cry1B, 6
	sound_ret
	audio_eng_channel SFX_Cry1B, 8
	sound_ret

; from audio/sfx/cry1c.asm
	audio_eng_channel SFX_Cry1C, 5
	sound_ret
	audio_eng_channel SFX_Cry1C, 6
	sound_ret
	audio_eng_channel SFX_Cry1C, 8
	sound_ret

; from audio/sfx/cry1d.asm
	audio_eng_channel SFX_Cry1D, 5
	sound_ret
	audio_eng_channel SFX_Cry1D, 6
	sound_ret
	audio_eng_channel SFX_Cry1D, 8
	sound_ret

; from audio/sfx/cry1e.asm
	audio_eng_channel SFX_Cry1E, 5
	sound_ret
	audio_eng_channel SFX_Cry1E, 6
	sound_ret
	audio_eng_channel SFX_Cry1E, 8
	sound_ret

; from audio/sfx/cry1f.asm
	audio_eng_channel SFX_Cry1F, 5
	sound_ret
	audio_eng_channel SFX_Cry1F, 6
	sound_ret
	audio_eng_channel SFX_Cry1F, 8
	sound_ret

; from audio/sfx/cry20.asm
	audio_eng_channel SFX_Cry20, 5
	sound_ret
	audio_eng_channel SFX_Cry20, 6
	sound_ret
	audio_eng_channel SFX_Cry20, 8
	sound_ret

; from audio/sfx/cry21.asm
	audio_eng_channel SFX_Cry21, 5
	sound_ret
	audio_eng_channel SFX_Cry21, 6
	sound_ret
	audio_eng_channel SFX_Cry21, 8
	sound_ret

; from audio/sfx/cry22.asm
	audio_eng_channel SFX_Cry22, 5
	sound_ret
	audio_eng_channel SFX_Cry22, 6
	sound_ret
	audio_eng_channel SFX_Cry22, 8
	sound_ret

; from audio/sfx/cry23.asm
	audio_eng_channel SFX_Cry23, 5
	sound_ret
	audio_eng_channel SFX_Cry23, 6
	sound_ret
	audio_eng_channel SFX_Cry23, 8
	sound_ret

; from audio/sfx/cry24.asm
	audio_eng_channel SFX_Cry24, 5
	sound_ret
	audio_eng_channel SFX_Cry24, 6
	sound_ret
	audio_eng_channel SFX_Cry24, 8
	sound_ret

; from audio/sfx/cry25.asm
	audio_eng_channel SFX_Cry25, 5
	sound_ret
	audio_eng_channel SFX_Cry25, 6
	sound_ret
	audio_eng_channel SFX_Cry25, 8
	sound_ret

; from audio/sfx/unused_cry.asm
	audio_eng_channel SFX_UnusedCry, 5
	sound_ret
	audio_eng_channel SFX_UnusedCry, 6
	sound_ret
	audio_eng_channel SFX_UnusedCry, 8
	sound_ret
