; Auto-generated by tools/relocate_text.py.
; Do not edit by hand; re-run the tool.

RelocatedText_CeladonCityGramps2Text:
	text "トホホ<⋯>！"
	line "スロットで　また　まけた！"

	para "コインが　たまったら"
	line "けいひんに　した　ほうが　ええと"
	cont "わかって　おったのに<⋯>！"
	done

RelocatedText_CeladonCityTrainerTips1Text:
	text "<⋯>　おとくな　けいじばん！"

	para "ヨクアタールは　わざの"
	line "めいちゅう　りつ　を　あげる！"

	para "クリティカッターは　わざが"
	line "きゅうしょに　あたり　やすくなる"

	para "アイテムの　おかいもとめは"
	line "タマムシ　デパートで　どうぞ！"
	done

RelocatedText_CeladonCityTrainerTips2Text:
	text "<⋯>　おとくな　けいじばん！"

	para "エフェクトガードは"
	line "ほのお　や　みず　でんき　など"

	para "とくしゅな　こうげき　から"
	line "#を　まもって　くれる！"

	para "アイテムの　おかいもとめは"
	line "タマムシ　デパートで　どうぞ！"
	done

RelocatedText_CeladonGymRainbowBadgeInfoText:
	text "レインボー　バッジで"
	line "レベル５０　までの　#が"
	cont "おとなしく　いうこと　きき　ます"

	para "そして<⋯>　かいりきの　わざが"
	line "たたかって　なくても　つかえます"

	para "それから<⋯>"
	line "よろしかったら"
	cont "これも　おつかいに　なって！"
	done

RelocatedText_CeladonMansionRoofHouseHikerText:
	text "こくばんにも　かいたが<⋯>"
	line "わしに　わからぬ　ことは　ない"
	cont "ゲームボーイの　なかに"
	cont "せかいが　あることも！"

	para "ぜひ！　ともだちを　さそって"
	line "#の　こうかんを"
	cont "たのしんで　くれたまえ！"
	done

RelocatedText_CeladonMart1FDirectorySignText:
	text "１かい<⋯>サービス·カウンター"

	para "２かい<⋯><TRAINER>ズ·マーケット"

	para "３かい<⋯>テレビ　ゲーム　ショップ"

	para "４かい<⋯>ワイズマン·ギフト"

	para "５かい<⋯>ドラッグ　ストア"

	para "おくじょう<⋯>じどう　はんばいき"
	done

RelocatedText_CeladonMart3FGameBoyKid3Text:
	text "はやく　きて！"
	line "ゴースト　ちゃーん！"

	para "ぼくは"
	line "ゴースト　マニア　なのね！"

	para "<⋯>　あー？"

	para "てんそう　されて　きた　ゴーストが"
	line "べつの　#に！？"
	done

RelocatedText_CeladonMart4FCurrentFloorSignText:
	text "４かい<⋯>まごころ　おくろう！"
	line "　　ワイズマン·ギフト　ショップ！"

	para "ただいま　#　しんかのいし"
	line "とくべつ　はんばい　ちゅう！"
	done

RelocatedText_CeladonMart4FYoungsterText:
	text "ちょっと　いい　はなし　きいたよ"

	para "#が　とびだして　きた　とき"
	line "ピッピにんぎょうを　なげると"
	cont "#は　それに　きを　とられる"

	para "つまり　にげれるって　ことだよ！"
	done

RelocatedText_CeladonMart5FGentlemanText:
	text "#の　のうりょくを　あげる"
	line "アイテムは　ここでしか　かえない"

	para "リゾチウムは"
	line "とくしゅ　のうりょくを　アップ"

	para "インドメタシンは"
	line "すばやさを　アップ　させるのだ"
	done

RelocatedText_CeladonMart5FSailorText:
	text "#の　のうりょくを　あげる"
	line "アイテムを　かいに　きたんだ！"

	para "タウリンは"
	line "こうげき　りょく　アップ！"

	para "ブロムヘキシンは"
	line "ぼうぎょ　りょく　アップ　だぜ！"
	done

RelocatedText_CeruleanCityGuardText:
	text "かわいそーな　ことに"

	para "この　いえは"
	line "ドロボーに　はいられたんだ！"
	cont "はんにんは　わかっとる！"
	cont "<ROCKET>の　しわざだ！"

	para "けいさつ　としても"
	line "<ROCKET>の　あくじ　には"
	cont "ほとほと　こまっとるのだ！"
	done

RelocatedText_CeruleanCitySuperNerd3Text:
	text "ここは<⋯>　ハナダ　どうくつ！"
	line "こわい　ほど　つよい　#が"
	cont "せいそく　してるぞ！"

	para "#　リーグ　にんてい"
	line "チャンピオン　しか　はいれないのだ！"
	done

RelocatedText_CeruleanGymMistyCascadeBadgeInfoText:
	text "ブルー　バッジが　あれば"
	line "レベル３０までの　#は"
	cont "おとなしく　いうこと　きくわ！"

	para "それが　たとえ"
	line "ひとから　もらった　#でもね"

	para "それと　たたかって　なくても"
	line "いあいぎりが　つかえるわ"

	para "ほそい　きを　きりたおして"
	line "とおれる　ように　なるの"

	para "<⋯>　あと　これは　わたしの"
	line "じまんの　<TM>よ！"
	done

RelocatedText_CeruleanMartCooltrainerMText:
	text "むしよけスプレーは"
	line "むし　どころか"
	cont "#も　よって　こないよ"

	para "つよい　#を　いちばん"
	line "うえに　おいて　おけば"
	cont "こうかは　ばいぞう　だ！"
	done

RelocatedText_CeruleanPokecenterGentlemanText:
	text "きみも"
	line "マサキの　うわさ　きいてるか？"

	para "みんなが　あいつを"
	line "#　マニアと　よんでるよ！"

	para "でも　ものを　あつめたり"
	line "じまん　したい　きもちは"
	cont "だれでも　ある！"

	para "みんなも　うらやましいんだな！"
	done

RelocatedText_CeruleanPokecenterSuperNerdText:
	text "マサキの　ヤツ！"

	para "めずらしい　#を"
	line "てに　いれる　ためには<⋯>"

	para "あんな　ことも　こんな　ことも"
	line "へいきで　するって　きいたよ！"
	done

RelocatedText_CeruleanTradeHouseGrannyText:
	text "うちの　じいさま"
	line "#の　こうかんに　こってるの"

	para "ぼうや"
	line "#　ずかん　あつめてるなら"

	para "こうかんの　あいて"
	line "して　あげて　くれるかしら"
	done

RelocatedText_ChampionsRoomOakComeWithMeText:
	text "オーキド『<PLAYER>！"

	para "#　リーグを　せいは　したのは"
	line "ひとりの　ちから　では　ないことを"
	cont "<⋯>　おまえは　わかっとるな！"

	para "<PLAYER>と　#の"
	line "ぜつみょうな　コンビネーション！"
	cont "みごと　だったぞ！"

	para "それでは<⋯>　<PLAYER>！"
	line "わたしに　ついて　きなさい！"
	done

RelocatedText_ChampionsRoomOakDisappointedWithRivalText:
	text "オーキド『<RIVAL><⋯>！"
	line "<⋯>　ざんねんだ！"

	para "おまえが　してんのうに　かったと"
	line "きいて　ここに　とんで　きたのに"

	para "#　リーグに　ついて　みたら"
	line "おまえは　まけとった！"

	para "<RIVAL>よ<⋯>！"
	line "なぜ　まけたのか　わかるか？"
	cont "<⋯>　<⋯>　<⋯>"

	para "おまえが　#　たちへの"
	line "しんらいと　あいじょうを"
	cont "わすれとる　からだ！"

	para "それでは　どんなに　がんばっても"
	line "トップ　には　たてんぞ！"
	done

RelocatedText_CinnabarGymBlaineVolcanoBadgeInfoText:
	text "うおーす！"

	para "この　クリムゾン　バッジは"
	line "もってる　だけで"

	para "#の　とくしゅ　のうりょくを"
	line "たかめる　こうかが　ある！"

	para "それから！"
	line "この　<TM>を　うけとれい！"
	done

RelocatedText_CinnabarLabFishingGuruText:
	text "ここでは　まいにち"
	line "#の　けんきゅうを　してます"

	para "あと　めずらしい　#などを"
	line "もちこんでくる　おきゃくさんも"
	cont "いらっしゃい　ますね"
	done

RelocatedText_CinnabarLabMetronomeRoomPCText:
	text "<PC>に"
	line "でんしメールが　とどいてる！"

	para "<⋯>　<⋯>　<⋯>"

	para "でんせつの　とり#は"
	line "３しゅるい<⋯>　ファイヤー"
	cont "サンダー　フリーザー<⋯>"
	cont "しかし　どこに　いるのか"
	cont "まだ　わかって　ません"

	para "こんど　ハナダ　どうくつに"
	line "ちょうさに　いきます"
	cont "<⋯>　まずは　ほうこく　まで"
	cont "#　ちょうさ　たい"

	para "<⋯>　<⋯>　<⋯>"
	done

RelocatedText_CinnabarPokecenterCooltrainerFText:
	text "しんか　キャンセル　つかってる？"

	para "しんか　しようと　するのを"
	line "とちゅうで　やめさせて"
	cont "そのままの　かたちで"
	cont "そだてる　テクニックよ"
	done

RelocatedText_CinnabarPokecenterGentlemanText:
	text "きみには　ともだちは　いるかな？"

	para "ともだちと　こうかんして"
	line "もらった　#は"
	cont "とても　はやく　そだつと　いう"

	para "ためして　みる　かちは"
	line "あると　おもうがね"
	done

RelocatedText_CopycatsHouse1FMiddleAgedManText:
	text "<⋯>　こまった　ことに　むすめは"
	line "ひとの　まねが　すきでな！"

	para "しょっちゅう　ひとを　からかう　ので"
	line "きんじょ　じゃ"
	cont "モノマネ　むすめと　よばれとる！"
	done

RelocatedText_FightingDojoKarateMasterGivePokemonText:
	text "わしは　たしかに　まけた！"

	para "しかし　どうじょうの　かんばん"
	line "<⋯>　だけは！"
	cont "もって　いかないで　くれい！"

	para "かわりに　わしの　だいじな"
	line "かくとう　#を　わたす！"

	para "どうか！"
	line "すきな　ほうを　えらんで　くれい！"
	done

RelocatedText_FuchsiaBillsGrandpasHouseBillsGrandpaText:
	text "おや？　あんた"
	line "マサキの　ことを　しっとるのかね？"

	para "マサキは　わしの　まごじゃ！"

	para "ちいさい　ころから"
	line "ものを　あつめるのが　すきな"
	cont "こども　じゃった！"
	done

RelocatedText_FuchsiaGymKogaSoulBadgeInfoText:
	text "ピンク　バッジを　もって　おれば"
	line "おぬしの　#の"
	cont "ぼうぎょ　りょくを　あげる！"

	para "たたかって　ない　ときでも"
	line "なみのりの　わざを"
	cont "つかえる　ように　なる！"

	para "そうだ<⋯>！　これを　おぬしに！"
	done

RelocatedText_FuchsiaPokecenterCooltrainerFText:
	text "トキワの　にしに"
	line "ほそい　みちが　ある　でしょう"

	para "その　おくに　たってるのが"
	line "すべての　#　<TRAINER>を"
	cont "まとめる　そしき　#　リーグよ"
	done

RelocatedText_FuchsiaPokecenterRockerText:
	text "１ぴきだけ　そだてても"
	line "つよい　<TRAINER>に　なれない"

	para "おおくの　#を　"
	line "バランス　よく　そだてるのも"
	cont "たいへん　だけどな"
	done

RelocatedText_GameCornerMiddleAgedMan1Text:
	text "<⋯>　ここだけの　はなし<⋯>"

	para "この　ゲーム　じょうは"
	line "<ROCKET>の　おみせ　らしい<⋯>"
	cont "みんな　うわさ　しちょる<⋯>"
	done

RelocatedText_HallOfFameOakText:
	text "オーキド『<⋯>　おほんッ！"
	line "おめでとう！　<PLAYER>！"

	para "ここは<⋯>"
	line "れきだいの　#　リーグ"
	cont "<TRAINER>の　もとで<⋯>"

	para "かつやく　した　#　たちを"
	line "えいえんに　きろく　して"
	cont "たたえる　フロア　である！"

	para "#　<TRAINER>は　ここに"
	line "きろく　される　よろこびを"
	cont "でんどういり　と　よんで　いる！"

	para "<PLAYER>！　おまえは"
	line "はげしい　たたかいの　すえ"
	cont "リーグ　チャンピオンと　なった！"

	para "ここに　<PLAYER>の　なまえと"
	line "#　たちを　きろく　しよう！"
	done

RelocatedText_IndigoPlateauLobbyCooltrainerFText:
	text "このさきは　してんのうと"
	line "ひとりずつ　たたかうの！"
	cont "もし　かてたら　ドアが　ひらいて"
	cont "おくの　へやに　すすめるわ！"
	cont "がんばって！"
	done

RelocatedText_IndigoPlateauLobbyGymGuideText:
	text "おーす！"
	line "みらいの　チャンピオン！"

	para "#　リーグ　してんのうは"
	line "４にん　つづけて"
	cont "しょうぶ　する　ルールだ！"

	para "まけたら　ひとりめ　から"
	line "やりなおしに　なるぞ！"
	cont "これが　さいごだ！　がんばれよ！"
	done

RelocatedText_LavenderMartBaldingGuyText:
	text "おじさんが　さがしてる　のは<⋯>"

	para "#が　たたかってる　とき"
	line "のうりょくを　いちじ　てきに"
	cont "あげる　どうぐ　なんだが<⋯>"

	para "プラスパワー　ディフェンダー"
	line "スピーダー　スペシャルアップ<⋯>"

	para "<⋯>という"
	line "なまえ　なんだが　しらんかな？"
	done

RelocatedText_LavenderTownCooltrainerMText:
	text "ここは　#の　おはかで"
	line "ゆうめいな　タウンだ<⋯>"

	para "かっていた　#が　しんだとき"
	line "#　タワーに　もっていって"
	cont "めいふくを　いのるのさ<⋯>"
	done

RelocatedText_LavenderTownSuperNerdText:
	text "さいきん　#　タワーに"
	line "ゆうれいが　でる　らしいんだ<⋯>"

	para "どうも　<ROCKET>に　ころされた"
	line "#の　ゆうれい　らしい<⋯>"
	done

RelocatedText_MrFujisHouseMrFujiPokedexText:
	text "ごうか　しょうひんが　あたる！"
	line "げっかん　#の　とも"
	cont "ビッグ·プレゼント！"

	para "<⋯>おうぼ　ほうほうは"

	para "<⋯>あら　きりとって　ある！"
	done

RelocatedText_Museum2FGrampsText:
	text "１９６９ねん　７がつ　２０か！"

	para "じんるい"
	line "はじめて　つきに　たつ！"

	para "わしは　あの　ニュースが　みたくて"
	line "カラーテレビを　かったんじゃ！"
	done

RelocatedText_OaksLabOakMyInventionPokedexText:
	text "つくえの　うえに　あるのは"
	line "わしが　つくった　#ずかん！"

	para "みつけた　#の　データが"
	line "じどうてきに　かきこまれて"
	cont "ページが　ふえて　いく　という"

	para "たいへん　ハイテクな"
	line "ずかん　なのじゃ！"
	done

RelocatedText_OaksLabOakThatWasMyDreamText:
	text "この　せかいの　すべての"
	line "#を　きろくした"
	cont "かんぺきな　ずかんを　つくること！"

	para "それが　わしの　ゆめ　だった！"

	para "しかし　わしも　もう　ジジイ！"
	line "そこまで　ムリは　できん！"

	para "そこで　おまえ　たちには"
	line "わしの　かわりに"
	cont "ゆめを　はたして　ほしいのじゃ！"

	para "さあ　ふたりとも"
	line "さっそく　しゅっぱつ　してくれい！"

	para "これは　#の　れきしに　のこる"
	line "いだいな　しごとじゃー！"
	done

RelocatedText_OaksLabRivalLeaveItAllToMeText:
	text "<RIVAL>『よーし！　じいさん！"
	line "ぜんぶ　おれに　まかせなー！"

	para "<PLAYER>！"
	line "ざんねんだが　おまえの　でばんは"
	cont "まったく　ねーぜ！"

	para "そうだ！　うちの　ねえちゃん　から"
	line "タウンマップを　かりて　いこう！"

	para "<PLAYER>　には　かさない　ように"
	line "ねえちゃんに　いって　おくから"
	cont "おれんちへ　きても　むだ　だからな！"
	done

RelocatedText_PewterCityCooltrainerMText:
	text "ニビ　シティは"
	line "むしとり　しょうねん　みたいに"
	cont "ただの　しゅみで　#"
	cont "やってる　やつ　ばかり！"

	para "しかし　ニビ　#　ジムの"
	line "タケシは　ちがうぜ"
	done

RelocatedText_PewterCityPoliceNoticeSignText:
	text "<⋯>　チラシが　はって　ある！"

	para "さいきん　オツキミやまで"
	line "きちょうな　#の"
	cont "カセキを　ぬすみ　まくる"
	cont "あくとうが　います！"
	cont "あやしい　ひとを　みたら<⋯>！"
	cont "<⋯>　ニビ　けいさつ　まで"
	done

RelocatedText_PewterNidoranHouseMiddleAgedManText:
	text "うちの　#　よそもの"
	line "だから　き　むずかしいよ"

	para "よそもの　ってのは　ひとと"
	line "こうかん　した　#だよ"

	para "そだつのは　はやいが"
	line "ちからのない　<TRAINER>の"
	cont "いうことは　きかん！"

	para "バッジさえ　あれば<⋯>"
	done

RelocatedText_PewterSpeechHouseYoungsterText:
	text "ねむり　どく　やけど　マヒ<⋯>"
	line "#の　たいちょうが　わるいと"
	cont "つかまえ　やすいよ"
	cont "でも<⋯>　かならず　とれる"
	cont "わけじゃ　ないみたい"
	done

RelocatedText_PokemonTower2FChannelerText:
	text "おぬし！　まよい　さまよう"
	line "ゆうれいの　しょうたいは<⋯>"
	cont "われわれでも　つかめない！"

	para "もし　とくべつな　どうぐが<⋯>"
	line "シルフ　スコープさえ　あれば"
	cont "みやぶれるかも　しれないが<⋯>"
	done

RelocatedText_RocketHideoutB4FGiovanniHopeWeMeetAgainText:
	text "<⋯>　きみは　とても　だいじに"
	line "#を　そだてて　いるな"

	para "そんな　こどもに"
	line "わたしの　かんがえは"
	cont "とても　りかい　できないだろう"

	para "　<⋯>！"
	line "ここは　いちど　みを　ひこう！"

	para "きみとは　また　どこかで"
	line "たたかいたい　ものだ<⋯>！"
	done

RelocatedText_Route11Gate1FGuardText:
	text "#を　たくさん　とると"
	line "なまえを　つけて　あげるのに"
	cont "くろう　しちゃう　でしょ！"

	para "この　さきの　シオン　タウンに"
	line "#の　なまえを"
	cont "うらなって　くれる　ひとが　いるよ"

	para "#に　もっと　いい　なまえを"
	line "つけ　なおす　ことも　できるよ"
	done

RelocatedText_Route13TrainerTips2Text:
	text "<⋯>　おとくな　けいじばん！"

	para "どうぐ　ウィンドウで"
	line "セレクト　ボタンを　おすと"
	cont "どうぐの　ばしょを"
	cont "いれかえる　ことが　できる！"
	done

RelocatedText_Route17TrainerTips1Text:
	text "<⋯>　おとくな　けいじばん！"

	para "おなじ　#　おなじ　レベルでも"
	line "とるたびに　パラメータが　すこし"
	cont "ちがってて<⋯>　そだつと"
	cont "ちがいが　おおきく　なる！"
	done

RelocatedText_Route1Youngster2Text:
	text "みちに　だんさが　あるだろ！"

	para "とび　おりるのは"
	line "ちょっと　こわいけど<⋯>"

	para "マサラ　タウンに　かえる　ときは"
	line "はやく　かえれて　いいよ"
	done

RelocatedText_Route3SuperNerdText:
	text "ふう<⋯>"
	line "この　へんで<⋯>"
	cont "<⋯>　ひとやすみ　して　いこう"

	para "ハナダ　シティから"
	line "どうくつを　ぬけて　きたら"
	cont "<⋯>　つかれた"
	done

RelocatedText_SSAnne1FWaiterText:
	text "ボン　ジュール！"
	line "わたしは　このふねの　ボーイです"

	para "ごようを　なんなりと"
	line "おもうしつけ　ください！"

	para "<⋯>　<⋯>　<⋯>"
	line "<⋯>　むくちな　かた　ですね"
	done

RelocatedText_SSAnne2FRivalCutMasterText:
	text "<RIVAL>『いあいぎりの　めいじんが"
	line "ふねに　のってるって　いう　からよ"

	para "あって　みたら"
	line "これが　ただの　ふなよい　おやじ！"

	para "でも　この　わざが"
	line "また　つかえるんだよなー！"

	para "おまえも　あって　みると　いいぜ！"
	line "じゃー　あばよ！"
	done

RelocatedText_SSAnne2FWaiterText:
	text "この　ふねは　せかい　かくちの"
	line "#　<TRAINER>が　のってる"
	cont "あこがれの　ごうか　きゃくせん！"

	para "みなとに　つくたびに"
	line "しょうたい　された　<TRAINER>と"
	cont "こうりゅう　パーティを　してます"
	done

RelocatedText_SafariZoneNorthRestHouseScientistText:
	text "サファリ　ゾーン　ないに"
	line "おちてる　アイテムは"
	cont "もって　いって　いいんだよ！"

	para "でも　ぜんぶ　ひろって　たら"
	line "じかん　なくなっちゃう！"
	done

RelocatedText_SafariZoneNorthTrainerTips2Text:
	text "<⋯>　おとくな　けいじばん！"

	para "#は　くさむらの　なかに"
	line "このんで　かくれる！"

	para "なかなか　みつからない　ときは"
	line "くさむらを　ジグザグに　あるこう！"
	done

RelocatedText_SafariZoneWestFindWardensTeethSignText:
	text "<⋯>　おねがいの　けいじばん！"

	para "サファリ　ゾーンの　えんちょうが"
	line "この　あたりで"
	cont "いればを　なくし　ました！"

	para "みつけた　かたに　おれい　します"
	line "<⋯>　サファリ　ゾーン　じむ　きょく"
	done

RelocatedText_SaffronCityGentlemanText:
	text "<ROCKET>が　シルフ　おそって"
	line "だいじけんって　きいて！"
	cont "ピジョットで　とんで　きたッス"

	para "かいけつ　した<⋯>？"
	line "すんません！"
	cont "ねっからの　ヤジウマ　で！"
	done

RelocatedText_SaffronCityTrainerTips1Text:
	text "<⋯>　おとくな　けいじばん！"

	para "なんでも　なおしは"
	line "ねむり　どく　やけど　こおり<⋯>"
	cont "なんでも　なおします！"

	para "すこし　たかい　けど"
	line "ねむけざまし　どくけし　などを"
	cont "バラバラに　かうより　らくちん！"
	done

RelocatedText_SaffronCityTrainerTips2Text:
	text "<⋯>　おとくな　けいじばん！"

	para "しんせいひん　スーパーボールは"
	line "モンスターボール　より　かくじつに"
	cont "#を　つかまえます！"

	para "なかなか　つかまえ　られない"
	line "#には　こちらを　ためそう！"
	done

RelocatedText_SaffronGymSabrinaMarshBadgeInfoText:
	text "ゴールド　バッジで"
	line "レベル７０　までの　#が"
	cont "いうことを　ききます！"

	para "それ　いじょう"
	line "つよい　#は"
	cont "ソッポ　むいたり　ふてね　したり"
	cont "あつかいが　たいへん　です！"

	para "だけど　そだて　すぎなきゃ"
	line "そういう　しんぱいは　むようよ！"

	para "それから<⋯>！"
	line "<TM>を　もって　いって"
	done

RelocatedText_SaffronPidgeyHousePaperText:
	text "<⋯>　この　あいだ"
	line "ポイント　アップ　もらったの"

	para "すごく　つよい　わざって"
	line "パワー　ポイント　すくないけど"
	cont "これで　ふやせば　いいのね<⋯>？"
	done

RelocatedText_SilphCo11FGiovanniText:
	text "おお　<PLAYER>か？"
	line "また　あったな！"

	para "おれは　いま　シルフの　しゃちょうと"
	line "しごとの　はなしを　してるんだ"

	para "おとなの　せかいに"
	line "くちを　はさまないで　もらいたい"

	para "どうしても　というなら"
	line "いたいめに　あって　もらうぞ！"
	done

RelocatedText_SilphCo11FGiovanniYouRuinedOurPlansText:
	text "くそー　<⋯>しょうが　ない！"
	line "シルフは　ひとまず　あきらめよう！"

	para "しかし　"
	line "わが　<ROCKET>は　ふめつだ！"

	para "<PLAYER>！　すべての　#は"
	line "<ROCKET>の　ために"
	cont "そんざい　するのだ！"
	cont "そのことを　わすれるなよ！"

	para "では<⋯>！"
	line "おれは　たいさん　しよう！"
	done

RelocatedText_SilphCo7FRivalGoodLuckToYouText:
	text "ほんじゃま　<PLAYER>！"

	para "おれさまは"
	line "ひとあし　さきに　いくぜ！"

	para "#ずかん　やってる　うちに"
	line "どういう　#が　つよい　とか"
	cont "なにに　しんか　するか　とか"
	cont "わかって　きちゃったんだよねえ！"
	cont "おれって　てんさい？"

	para "ま<⋯>　そういう　ことで"
	line "これからは"
	cont "#　リーグの　してんのうを"
	cont "ばっさ　ばっさと　たおして"

	para "さいきょうの　<TRAINER>に"
	line "なってやろう　と　きめたのさ！"

	para "<PLAYER>も"
	line "せいぜい　がんばって　くれい"
	cont "じゃあな！"
	cont "バイビー！"
	done

RelocatedText_SilphCo7FRivalWaitedHereText:
	text "<RIVAL>『ひゃはは！"
	line "ここで　まってれば"
	cont "くるんじゃねえかと　おもったのさ"

	para "しかし　<ROCKET>　あいてに"
	line "てこずってる　みたいだな！"
	cont "ま<⋯>　おれさまには"
	cont "かんけいの　ないこと　だけど！"

	para "ヤマブキ　シティで　<PLAYER>が"
	line "あるいてんのを　ちょこっと"
	cont "みかけた　もの　だからさ"

	para "すこしは<⋯>　つよくなったのか"
	line "なあーんちゃって　おもってさあ！"
	done

RelocatedText_UndergroundPathRoute7CopyUnusedGirlText:
	text "「たまむし」シティの　デパートへ"
	next "かいものに　いきたいんだけど<⋯>"

	para "あのまちには　ガラのわるい　ひとが"
	line "おおくて　なんだか　こわいのよね"
	done

RelocatedText_VermilionCityGambler2Text:
	text "わし　じぬし！"
	line "この　しかくの　ばしょ"
	cont "ぜーんぶ　わしの　とち！"

	para "ここに　ビル　たてようと　おもって"
	line "#に　じならし　させとる！"
	done

RelocatedText_VermilionCityNoticeSignText:
	text "<⋯>　おしらせの　チラシだ！"

	para "さいきん<⋯>　１２ばん　どうろに"
	line "いねむり　#が　しゅつぼつ"
	cont "とおれない　ことが　あります！"

	para "そういう　とき　シオン　タウンへ"
	line "いく　かたは　いわやま　トンネルを"
	cont "とおって　ください！"

	para "<⋯>　クチバ　けいさつ　より"
	done

RelocatedText_VermilionGymLTSurgeThunderBadgeInfoText:
	text "オレンジ　バッジ　もってる　だけで"
	line "ユーの　#　スピード　アップ"

	para "アーンド！　そらをとぶ　わざは"
	line "ファイト　ない　ときも"
	cont "つかえる　ように　なるヨ！"

	para "ユーは　スペシャル！"
	line "これは　ミーの　きもちネ！"
	done

RelocatedText_VermilionMartCooltrainerMText:
	text "よのなか　には　#で"
	line "わるだくみを　する　やつらも　いる"

	para "#を　たかく　うりさばいたり"
	line "ときには　にんきがない　とか"

	para "やくに　たたない　という　りゆうで"
	line "ころして　しまったり"

	para "そういう　わるい　こと　ばかりする"
	line "あつまりが　ロケットだんさ"
	done

RelocatedText_VermilionPidgeyHouseLetterText:
	text "<⋯>ピピちゃん"
	line "こんど　あそびに　いきたい　です"

	para "ヤマブキ　シティでは　<ROCKET>の"
	line "じけんが　おおい　そうですね"

	para "クチバは　そうでも　ありません<⋯>"
	done

RelocatedText_ViridianCityTrainerTips1Text:
	text "<⋯>　おとくな　けいじばん！"

	para "とにかく　#を　つかまえて"
	line "ドンドン　ふやそう！"
	cont "<TRAINER>との　しょうぶも"
	cont "たくさん　もってると　ゆうり！"
	done

RelocatedText_ViridianCityTrainerTips2Text:
	text "<⋯>　おとくな　けいじばん！"

	para "#には　たいりょくの　ほか"
	line "わざを　くりだす　げんきの　もと"
	cont "パワーポイントが　あります"

	para "わざ　ごとの　パワーポイントが"
	line "なくなった　ときも"
	cont "#センターで　やすませて！"
	done

RelocatedText_ViridianCityYoungster1Text:
	text "きみが　こしに　つけてる"
	line "その　モンスターボールは<⋯>！"
	cont "まさしく　#だね！"

	para "いつでも　#の　だしいれが"
	line "じゆうに　できる　なんて"
	cont "べんりな　よのなかだね"
	done

RelocatedText_ViridianForestTrainerTips4Text:
	text "<⋯>　おとくな　けいじばん！"

	para "#を　つかまえる　ときは"
	line "なるべく　よわらせてから！"

	para "#が　げんきだと"
	line "にげるかも　しれないよ！"
	done

RelocatedText_ViridianGymGiovanniEarthBadgeInfoText:
	text "グリーンバッジさえ　あれば"
	line "どんなに　レベルの　たかい"
	cont "#も　いうことを　きく！"

	para "きみが　いちにんまえの"
	line "<TRAINER>に　なった　あかしだ！"

	para "これで　#リーグに"
	line "いどむ　ことが　できるだろう"

	para "この　<TM>は<⋯>！"
	line "#リーグへ　いどむ"
	cont "きみへ　せんべつだ！"
	done

RelocatedText_ViridianNicknameHouseBaldingGuyText:
	text "ニックネームを　かんがえることは"
	line "たのしい<⋯>が　むずかしい！"

	para "こった　ニックネームも　いいが"
	line "おぼえやすいのが　いちばん　やな！"
	done

RelocatedText_ViridianPokecenterGentlemanText:
	text "すみに　ある　<PC>は　どうぞ"
	line "ごじゆうに　おつかいください！"

	para "<⋯>と　うけつけの　ねーちゃんが"
	line "いっとった　しんせつやのう"
	done
