#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

OPTIONS_PATH = Path("constants/headroom_options.asm")

PROFILES: dict[str, dict[str, int]] = {
    "default": {
        "HEADROOM_STRIP_ALL_AUDIO": 0,
        "HEADROOM_STRIP_UNUSED_AUDIO": 0,
        "HEADROOM_STRIP_OPTIONAL_MUSIC": 0,
        "HEADROOM_STRIP_OPTIONAL_BATTLE_MUSIC": 0,
        "HEADROOM_STRIP_OPTIONAL_SFX": 0,
        "HEADROOM_STRIP_CORE_SFX": 0,
    },
    "unused-audio": {
        "HEADROOM_STRIP_ALL_AUDIO": 0,
        "HEADROOM_STRIP_UNUSED_AUDIO": 1,
        "HEADROOM_STRIP_OPTIONAL_MUSIC": 0,
        "HEADROOM_STRIP_OPTIONAL_BATTLE_MUSIC": 0,
        "HEADROOM_STRIP_OPTIONAL_SFX": 0,
        "HEADROOM_STRIP_CORE_SFX": 0,
    },
    "aggressive-audio": {
        "HEADROOM_STRIP_ALL_AUDIO": 0,
        "HEADROOM_STRIP_UNUSED_AUDIO": 1,
        "HEADROOM_STRIP_OPTIONAL_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_BATTLE_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_SFX": 1,
        "HEADROOM_STRIP_CORE_SFX": 0,
    },
    "extreme-audio": {
        "HEADROOM_STRIP_ALL_AUDIO": 0,
        "HEADROOM_STRIP_UNUSED_AUDIO": 1,
        "HEADROOM_STRIP_OPTIONAL_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_BATTLE_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_SFX": 1,
        "HEADROOM_STRIP_CORE_SFX": 1,
    },
    "no-audio": {
        "HEADROOM_STRIP_ALL_AUDIO": 1,
        "HEADROOM_STRIP_UNUSED_AUDIO": 1,
        "HEADROOM_STRIP_OPTIONAL_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_BATTLE_MUSIC": 1,
        "HEADROOM_STRIP_OPTIONAL_SFX": 1,
        "HEADROOM_STRIP_CORE_SFX": 1,
    },
}


def render(profile: str, options: dict[str, int]) -> str:
    lines = [
        "; Auto-generated by tools/headroom_profile.py",
        f"; Profile: {profile}",
        "",
    ]
    for key in sorted(options):
        lines.append(f"DEF {key} EQU {options[key]}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate constants/headroom_options.asm from a named headroom profile."
    )
    parser.add_argument(
        "--profile",
        choices=sorted(PROFILES),
        default="default",
        help="Headroom profile to apply (default: default)",
    )
    args = parser.parse_args()

    content = render(args.profile, PROFILES[args.profile])
    OPTIONS_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OPTIONS_PATH} with profile={args.profile}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
